### ISSUE TITLE
Removing data center entry because it is covered in IBM Style Guide

### ISSUE THREAD

**Issue by leswilliams44** [redhat-documentation/supplementary-style-guide#134]
Please consider deleting the entry for data center. The same guidance is provided on page 267 of the _IBM Style Guide_.

**Comment by bergerhoffer** [comment]
I'm okay with removing it, unless we think it's important to keep the part about marketing:

> Note that marketing publications use the one-word form, "datacenter."

**Comment by bergerhoffer** [comment]
We discussed this at the 15 December 2021 SSG meeting. Since there is some additional guidance about marketing using one word "datacenter", we decided to keep this entry. Although marketing doesn't necessarily use the ISG or SSG, it might be helpful if CCS associates come across marketing material with one word, so that they know it doesn't need to be changed there. Closing!
