### ISSUE TITLE
Reverse the order of information presented in the Graphical interfaces examples

### ISSUE THREAD

**Issue by jenmalloy** [redhat-documentation/supplementary-style-guide#156]
In the Graphical interfaces section (https://redhat-documentation.github.io/supplementary-style-guide/#graphical-interfaces), the order that information is presented in the example sentences should be reversed: 
* "Click *Metering* on the *Installed Operators* page."
* "Enter `test-postgresql` in the *Name* field." 

As a user, I first have to orient myself to "where," so I can then perform the action itself. So for a better user experience (and to reduce cognitive load), put the "where" first, then the "what": "On the *Installed Operators* page, click *Metering.*"

(Happy to contribute this change, but wanted to raise it as an issue first.)

**Comment by jenmalloy** [comment]
@bergerhoffer Will do, thanks!

**Comment by bredamc** [comment]
@bergerhoffer I spoke to Jen about this item, and I'll make this change along with the other changes I've volunteered for in issue 147. I plan to work on these changes tomorrow, so that we can discuss the PRs at the meeting on Wednesday. I don't seem to be able to assign it to myself, so please feel free to assign it to me :)

**Comment by bergerhoffer** [comment]
Sounds great, thanks @bredamc! I've assigned this issue to you.

**Comment by bredamc** [comment]
Fixed in https://github.com/redhat-documentation/supplementary-style-guide/pull/161

**Comment by bergerhoffer** [comment]
PR #161 has been merged - closing!
