### ISSUE TITLE
404 - Broken link 

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#157]
This page [Guidelines for Red Hat Documentation](https://redhat-documentation.github.io/) has a broken link for the Supplementary Style Guide, although it calls the guide: Glossary of Terms and Conventions for Product Documentation, so obviously the whole page is out of date. We should update the page or hide it. 

Here's the broken link's URL: https://redhat-documentation.github.io/glossary-of-terms-and-conventions-for-product-documentation/

At the very least, we should have a redirect for that URL.

**Comment by inoxx03** [comment]
Thank you for reporting this @IngridT1 

The link to the guide should be: https://redhat-documentation.github.io/supplementary-style-guide 

If we want to point specifically to the glossary section, then we can also use: https://redhat-documentation.github.io/supplementary-style-guide/#glossary-terms-conventions

It seems that the site in question (https://redhat-documentation.github.io/) is still actively maintained [in this repository](https://github.com/redhat-documentation/redhat-documentation.github.io). The latest updates are from January 10th 2022.

I think that, in this case, updating the site would be preferable to hiding it/setting up a redirect, because we have access to the source of the site and  there are a few more things in addition to the broken URL that could use some attention (for example, the name by which the site refers to the SSG is not really accurate).

If we decide on going forward with this, I can take a look at updating the site sometime this week.

CC @bergerhoffer

@redhat-documentation/ccs-style-council Thoughts?

**Comment by stoobie** [comment]
:^D
@IngridT1 @inoxx03 @bergerhoffer @redhat-documentation/ccs-style-council 
A few days ago I noticed this and created an issue and a PR to fix it. Currently awaiting merge. See https://github.com/redhat-documentation/redhat-documentation.github.io/issues/12 and https://github.com/redhat-documentation/redhat-documentation.github.io/pull/13.

**Comment by inoxx03** [comment]
thanks @stoobie, the PR looks great!
Not sure who owns the [repo](https://github.com/redhat-documentation/redhat-documentation.github.io) or who has merge rights on it, either.

**Comment by bergerhoffer** [comment]
Awesome thanks @stoobie! I have merge rights on that repo, so I can merge your PR there when it's ready. 

I added two comments on the PR if you wouldn't mind taking a look.

**Comment by bergerhoffer** [comment]
Closing this issue - the broken link on that page was fixed by https://github.com/redhat-documentation/redhat-documentation.github.io/pull/13.
