### ISSUE TITLE
Add guidance for qualifying product, package, and component names

### ISSUE THREAD

**Issue by jafiala** [redhat-documentation/supplementary-style-guide#169]
We have no guidance in RH SSG or in IBM on qualifying product, package, and component names at first occurrence.

We should add what is the recommended practice, that is to qualify the name at first occurrence in a module, probably to the "Product names and version references" section.

**Comment by bergerhoffer** [comment]
@jafiala I think that this came from something out of the peer review initiative, but I can't remember exactly what. Can you provide some more information and examples of what you're requesting here?

**Comment by spank50** [comment]
Does this refer to how we qualify the product name in the documentation matches the Red Hat product names as described in
Official Red Hat product and solution names list - Google Sheets
https://docs.google.com/spreadsheets/d/1DLS_lS3VKidgZIvcLmLp9BoiqptkvqHWfe1D5FD2kfk/edit#gid=1987148185

**Comment by bergerhoffer** [comment]
If I remember correctly, it had something to do with clarifying what something is, like saying "the `<xyz>` utility" the first time, instead of just calling it `<xyz>`.

An example might be something like "You must the `sudo` command to" (instead of saying "You must use `sudo` to..."). But definitely need confirmation on this.

**Comment by jherrman** [comment]
@bergerhoffer , IBM Style Guide defines the rule for "command, parameter, or option" - so it does not really include application names, package names, UI elements, keys, and other named things that may require qualification. This leaves quite a lot of space for inconsistencies. In addition, even in the cases they do specify, I don't think adhering to it 100% is really warranted.

For example, here's a frequent pattern for a release note description:

> When using the `X` command with the `--Y` option, `X` failed. This update fixes how `X` handles `--Y` and the problem no longer occurs.

If you describe it with the names expanded, the text becomes longer, more awkward to read, and doesn't really gain anything in terms of clarity:

> When using the `X` command with the `--Y` option, the `X` command failed. This update fixes how the `X` command handles the `--Y` option and the problem no longer occurs.

Similarly, if you rewrite Honza's above example with qualifiers used every time, you get an overlong RN title and a repetitive description:

>The GnuTLS library no longer rejects SHA-1-signed CAs if they are explicitly trusted
>
> Previously, the GnuTLS library checked signature hash strength (...) With this update, the GnuTLS library excludes trusted CAs (...)

Finally, skimming through some of our docs, adhering to "classify everything all the time" rule would probably require a not-insignificant amount of rewrites across the board that would mostly just amount to word count bloat with near-zero added value for the reader.

With all these in mind, I'd suggest creating a new sub-section under [Structure](https://redhat-documentation.github.io/supplementary-style-guide/#structure), named "Qualification" (or maybe "Classification"?), with the following content:

> When using the name of a software element, such as a package, utility, command, parameter, or option, make sure the first occurrence is expanded with an appropriate qualification term.
>
> [Green check] Use the `dnf update` command.
>
> [Red X] Use `dnf update`.
>
> In subsequent occurrences within the same piece of content (such as a module or a release note), you can omit the qualifying term if the context makes it clear you are still describing the same element.
>
>Examples:
>
>[Green check] RHEL 9.1 adds the `virtiofs` utility. Using `virtiofs`, you can share files between your host system and its virtual machines. To configure `virtiofs`, see the procedure below.
>
>[Green check] To enable the `virt-install` command, install the `virt-install` package.
>
>[Red X] With this update, `sysctl` is installed with `procps-ng` and uses the same syntax for arguments as `systemd-sysctl`.

The point of the rule in IBM SG is clarity in terminology, which would still be maintained. In addition, with this approach, we'd have improved adherence to minimalism, better readability, and also being more intuitive for writers (since it follows the same pattern as expanding acronyms).

**Comment by bergerhoffer** [comment]
Hi @jherrman, we can definitely bring this back up at the next SSG meeting and discuss whether they need to be qualified each time, or only upon first use in a [sentence | paragraph | module]. The IBM Style guidance starts with "Generally," which leaves some flexibility, and has a few exceptions listed, but not this. 

It sounds reasonable to me to identify it upon first use, at least in a paragraph, maybe even a module. But we'll talk about it to see if there are any good reasons why it should be named each time. Feel free to attend the meeting if you'd like (August 30).

Reopening this issue!

**Comment by bburt-rh** [comment]
In the style council meeting on Aug. 29, the majority of attendees voted to take no action in the SSG regarding this issue, so I am closing this issue.
