### ISSUE TITLE
Guidance against using "foo" and "bar"

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#177]
I've always heard against using the terms "foo" and "bar" (and "foobar") in our docs. But we can't find any official guidance in the ISG or SSG not using it.

It looks like an older version of the ISG print version had foo, foobar as terms to not use:

> foo, foobar  _n_
>  Do not use. These terms are variants of an acronym of a profanity that is sometimes used by developers in code. If you see either term in sample code, revise the sample or do not publish it. Rewrite any text to omit these terms.

But the new PDF/online version of the ISG do not have this term listed at all. @lahinson was going to check in to see if she can find the history on why it's no longer there.

In the meantime, would like to see what the SSG council thinks on this, if we should add it to the SSG. And also what good alternatives to suggest would be. "foo" seems like you could use "example" pretty easily, but not sure what to do about the pair "foo" and "bar". Thoughts?

**Comment by bergerhoffer** [comment]
+1 for not adding it to the SSG if the ISG will be adding entries.

Though I'd also be interested to know if we have any recommended alternatives that we could share.

**Comment by sterobin** [comment]
@bergerhoffer Since the best alternatives would be actual examples or at least real words,  I don't know if we need or should have global alternatives for terms to use in the SSG. I think leaving it with what the ISB says or will say is sufficient. If there's recurring confusion about it, I suppose we could just give a brief entry of basic examples where the writer uses real words instead of foobar. So maybe we wait until the ISG is updated with it and then assess the need from there, based on continued CCS concerns.

Side note, regardless of whether or not it for certain derives from profanity (to @mportman12 's point), it's still an unhelpful practice and falls on the same kind of line as Latinate terms and abbreviations and other unclear formations that we're supposed to avoid anyway.

**Comment by mportman12** [comment]
@lahinson How about:
"Do not use. These terms are technical jargon and are sometimes used by developers in code."
Because the origin is debatable, I think banning the terms because of a possible profanity origin is besides the point - it's technical jargon and, as @sterobin said, falls in the unclear forms and abbreviations we should strive to avoid.

**Comment by lahinson** [comment]
Thanks, @sterobin and @mportman12! I'll pass your suggestions over to the IBM Style Council.

**Comment by Srivaralakshmi** [comment]
Hi, @lahinson! Thanks for stepping up to pass the suggestions to the IBM Style Council. Any updates so far?
Interested to know about any recommended alternatives that we can use.
Thanks!

**Comment by lahinson** [comment]
Hi @Srivaralakshmi! I haven't heard from the IBM Style Council yet, but I sent them an email this morning to check in. I'll let you know when I have an update.

**Comment by Srivaralakshmi** [comment]
That's great! Sure. Thanks, @lahinson for the update :)

**Comment by lahinson** [comment]
The IBM Style Council updated the [Word usage page](https://www.ibm.com/docs/en/ibm-style?topic=word-usage) with these changes:

- Updated the entry for "fubar" per @mportman12's suggestion
- Added an entry for "foo" that points to the "fubar" entry

Here's a screen cap of the new "foo" entry:

![Screen Shot 2022-05-06 at 10 25 53 AM](https://user-images.githubusercontent.com/102675557/167153305-d2e06d72-99f0-4c65-b1cb-848c2215d374.png)

The council didn't provide any suggestions for alternatives, as they felt that what a team might use for an alternative would vary based on the context. If there's a great interest in having a list of potential alternatives, we need to gather a few examples of where "foo" is currently being used. We'll send the examples to the council so that they can take a look and make an informed decision on reasonable alternatives.

**Comment by mportman12** [comment]
@bergerhoffer Because ISG has added an entry, can we close this issue without making changes on the SSG side? I think the ISG covered all of our concerns.

**Comment by bergerhoffer** [comment]
Sorry for the delay all, this sounds great. Thanks @lahinson for connecting with the IBM style council to have them make those updates!

Closing this issue.
