### ISSUE TITLE
Incorporate EAP terminology and usage

### ISSUE THREAD

**Issue by bobjohnsrh** [redhat-documentation/supplementary-style-guide#18]
An update to the EAP terminology and usage guidelines was completed immediately before the supplemental style guide project began.  Terminology and usage specific to EAP should be incorporated into the supplemental style guide.  

The draft source for the update is here:  https://gitlab.cee.redhat.com/bobjohns/draft-content

One additional section should be added regarding EAP subsystems.  

Content that duplicates content from the supplemental style guide should not be ported to the new project.  Only the EAP-specific terminology and usage should be ported.

**Comment by bergerhoffer** [comment]
@bobjohnsrh thanks for opening this! 

For the A-Z terms, you should be able to open a PR and update the existing JBoss EAP-specific terms section. Other than a review of the PR, it shouldn't need too much discussion, since it is product-specific. You can add/update as necessary: https://github.com/redhat-documentation/supplementary-style-guide/blob/master/supplementary_style_guide/glossary_terms_conventions/product_conventions/jboss-eap.adoc.

For the rest of the guidance that your draft has, I would request you to open individual issues for each one, so that we can consider and discuss each individually. If the item's recommendation is to follow the IBM style guide, as I see some of them are, then there's no need to open an issue for it. And same with if it is already being covered as an item in this supplementary style guide, then there's no need to open one. Unless you have additional considerations to add to the current recommendation.

**Comment by leswilliams44** [comment]
@bobjohnsrh, Is there anything we can do to help you move forward with this issue?

**Comment by bobjohnsrh** [comment]
@leswilliams44 I've been asked to prioritize work I am doing for the EAP doc team. I can work on this once I get that work finished.

**Comment by leswilliams44** [comment]
@bobjohnsrh , Thanks, just checking as part of my admin duties

**Comment by inoxx03** [comment]
Hi @bobjohnsrh is there any way we can help you in completing this issue? If you are still engaged in release work on EAP and need more time before you can work on this that's ok:)  I'm checking progress on all open issues as required by my admin duties.

**Comment by leswilliams44** [comment]
Hi, @bobjohnsrh: Is there any way we can help you with this issue?

**Comment by bergerhoffer** [comment]
A draft for this was started in #55 but needs additional work. Will follow up with the EAP team.

**Comment by bergerhoffer** [comment]
This was handled by #97, which has merged. Updates are live: https://redhat-documentation.github.io/supplementary-style-guide/#_red_hat_jboss_enterprise_application_platform
