### ISSUE TITLE
Capturing issues found during the reorg eval: OpenShift

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#195]
Capturing OpenShift issues noticed during the reorg. Need to follow up after the reorg:

- [ ]  ~~Some OpenShift terms were general, but still had some OCP-specific info. Consider whether those should just be removed, for example: image~~
- [x]  Does OCS need to be updated to new name of ODF?
- [ ]  "OpenStack services" isn't actually a term, but is guidance on how to write them generically. I had pulled the OCP "API objects" entry for the same reason. Didn't add it in for now, but consider whether to keep this (and the OCP one), or keep excluding them.

**Comment by lahinson** [comment]
Hi @bergerhoffer - I'm happy to help with this one, but I don't seem to have access to assign it to myself.

**Comment by bergerhoffer** [comment]
Thanks @lahinson I assigned it to you!

**Comment by mportman12** [comment]
@lahinson Can this issue be closed?

**Comment by bergerhoffer** [comment]
@mportman12 The only item left that is valid is that we removed how to refer to OpenStack services (since it wasn't an actual entry for the term "OpenStack services", but instead was guidance on how to refer to them. We removed a similar entry on "API objects" for OpenShift. 

I think that if no one has complained yet about these removals, then they aren't critical. We can always revisit if we get complaints that they need to be included. Closing!
