### ISSUE TITLE
SSG requires "through" for numerical ranges, request to revise this guidance

### ISSUE THREAD

**Issue by jeana-redhat** [redhat-documentation/supplementary-style-guide#199]
The supplementary style guide [says](https://redhat-documentation.github.io/supplementary-style-guide/#_t
):

> Use "through" instead of a hyphen or any other type of dash when expressing a range.

Contrast with IBM [guidance](https://www.ibm.com/docs/en/ibm-style?topic=measurement-numbers#ranges):

> Generally, use an en dash (–) without spaces on each side to indicate a range of numbers.

In the opinion of both myself and other members of the OCP docs team, using a dash to indicate a range of numbers is infinitely more readable for us, and likely would be for anyone who has a technical background. (h/t @bscott-rh)

Further, @maxwelldb dug around and found the [PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/1) that introduces this item - he notes that there is not a specific rationale provided for this item, and therefore we speculate that this might be worth revising.

Thank you for your consideration! :bow:

**Comment by maxwelldb** [comment]
h/t @dfitzmau for this, but this guidance might be a good accessibility tweak. If we can't verify that screenreaders interpret number ranges w/dashes successfully, I strongly prefer SSG here.

**Comment by mportman12** [comment]
@jeana-redhat The [PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/1) you cited appears to be one of the initial commits to create the SSG in GitHub, so I don't think it's particularly notable that no explanation was given about the `through` entry.

I dug into the ISG entry and found this from the ISG History page for November 2021:

> Dashes, Dates and times, and Hyphens: Do not use hyphens for ranges, use en dashes instead. The guidance for dashes and hyphens has been updated to bring IBM Style into alignment with the IBM Design Language and our default reference, The Chicago Manual of Style. The new guidance specifies to use en dashes instead of space-hyphen-space for ranges and provides examples. Pages updated: Dashes, Dates and times, and Hyphens.

While this info doesn't provide clarity into why SSG recommends using `through` over hyphens or en dashes, I think it's useful to know that ISG is in line with current Chicago Manual of Style conventions. Prior to this change, ISG recommended using hyphens instead of the word `through` for ranges. I also dug up a 2015 copy of ISG that also recommended hyphens for ranges, so ISG has recommended not using the word `through` for ranges for a very long time.

All of this is to speculate that SSG must have either had a very good reason/use case to recommend the word `through` over a hyphen or en dash, or this recommendations dates back to a long time ago and needs to be updated.

**Comment by dfitzmau** [comment]
I found this entry in the Chicago Manual of Style:

> En dash as "to." The principal use of the en dash is to connect numbers
> and, less often, words. With continuing numbers—such as dates, times,
> and page numbers—it signifies up to and including (or through). For the
> sake of parallel construction, the word to or through (or until), never the
> en dash, should be used if the word from precedes the first element in
> such a pair; similarly, and should be used if between precedes the first
> element.

Perhaps this paragraph will clarify the when question?

**Comment by bergerhoffer** [comment]
So @mportman12 is correct that this "through" guidance wasn't something that we (CCS) came up with and added. It came in during the initial port/creation of the SSG, where we did pull in a lot of the terms from stylepedia.net. So that is where the guidance would have originated from.

The SSG entry in question here is a glossary entry [1], but is really acting like style guidance. 

But based on what I'm seeing, we don't really have any good reason why we would have wanted to purposefully deviate from the IBM style guide on this topic. It seems that Patternfly also allows the use of en dash for ranges [2].

I recommend that we remove the "through" glossary entry. @redhat-documentation/ccs-style-council thoughts?

[1] https://redhat-documentation.github.io/supplementary-style-guide/#through
[2] https://www.patternfly.org/v4/ux-writing/punctuation/#em-dash-en-dash-hyphen

**Comment by daobrien** [comment]
To which case of "through" in the RH guide are you referring? If it's incorrect (deviates from IBM for no good reason) then we need to update it. Thanks

**Comment by bergerhoffer** [comment]
@daobrien The "through" entry being discussed in this issue is the one here in the supplementary style guide: https://redhat-documentation.github.io/supplementary-style-guide/#through

**Comment by daobrien** [comment]
> @daobrien The "through" entry being discussed in this issue is the one here in the supplementary style guide: https://redhat-documentation.github.io/supplementary-style-guide/#through

Thanks @bergerhoffer I thought you were referring to an entry in the RH Style Guide that was somehow incorrect.
cheers

**Comment by bergerhoffer** [comment]
> > @daobrien The "through" entry being discussed in this issue is the one here in the supplementary style guide: https://redhat-documentation.github.io/supplementary-style-guide/#through
> 
> Thanks @bergerhoffer I thought you were referring to an entry in the RH Style Guide that was somehow incorrect. cheers

@daobrien Nope, the issues in this repository are all about the RH supplementary style guide used by CCS.

**Comment by bergerhoffer** [comment]
@redhat-documentation/documentation-conventions Any +1s or objections to removing the "through" entry? https://redhat-documentation.github.io/supplementary-style-guide/#through

**Comment by lahinson** [comment]
I've added this item to the agenda of the upcoming IBM Style/Red Hat meeting to determine whether the IBM Style Council considered accessibility when they decided the guidance to use an en dash instead of "through".

**Comment by bergerhoffer** [comment]
Discussed at the 30 November meeting.

Mostly people were in favor of removing our specific guidance here, and following the IBM style guide on number ranges. But there were some concerns about whether the dashes were not good for accessibility - how they would be read by a screen reader.

As @lahinson mentioned, we're going to bring this up with the IBM style council to see whether accessibility was a consideration when allowing dashes in number ranges. Marking this issue with the "IBM input needed" label. 

Some CCS folks might also do some testing to see how this would be read.
