### ISSUE TITLE
Project and to project?

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/supplementary-style-guide#220]
Clarify/allow/disallow usage of the verb `project` as part of the https://redhat-documentation.github.io/supplementary-style-guide/#project entry.

See my comment https://github.com/openshift/openshift-docs/pull/49201/files#r965890729 for the reasons for raising this issue.

**Comment by bergerhoffer** [comment]
So I see the issue here, and I agree in the above PR that it's best to avoid using the verb "project" to avoid confusion with the noun "project" that is used frequently throughout the OpenShift docs. 

However, I'm uncertain as to whether we really should add an entry to avoid the verb "project", since it's such a special case, and not technically wrong. Would be interested in hearing what other @redhat-documentation/ccs-style-council members think

**Comment by bburt-rh** [comment]
I agree with @max-cx and @bergerhoffer that when used together, the two can be potentially confusing, and we should avoid "project" for this reason. The linked PR is an interesting case because the verb "project" as used in the PR does not seem to be correct usage for the context: I don't think that data can be "projected". I've heard of data being sent or data being broadcast or data being stored, but never "projected." 

All of that being said, I don't agree that it needs a separate entry on it's own. But I do think it might be worth considering adding a more generic admonition to "avoid homographs in close proximity to each other" and then list some common homographs that might be confusing like "project", "block", "close", "number", "attribute", "coordinates", and "minute" (those are the only ones that spring to mind at the moment, but there are probably others).

**Comment by bergerhoffer** [comment]
I really like the suggestion of adding general guidance of avoiding homographs in close proximity, with a list of examples. What do others think?

**Comment by bburt-rh** [comment]
If people agree that a new entry for homographs would be a useful addition, here's some proposed text for an entry:

```
A homograph is a word that is spelled the same as another word but has a different meaning. Using homographs in close proximity in a sentence or paragraph might confuse readers. Therefore, avoid using homographs in these situations. 

Homographs that commonly appear in technical documentation include the following:
- attribute
- block
- close
- coordinates
- minute
- number
- project
```

**Comment by Amrita42** [comment]
I love the idea of adding Homograph as an entry.

**Comment by bergerhoffer** [comment]
@max-cx What do you think of @bburt-rh's proposal?

**Comment by bburt-rh** [comment]
@max-cx I can submit a PR with my proposed change, unless you have objections.

**Comment by max-cx** [comment]
@bburt-rh and @bergerhoffer, OK, thank you!

**Comment by bburt-rh** [comment]
Thanks, @max-cx - I'll submit a PR and link it to this issue, which will close automatically when the PR merges.

**Comment by bburt-rh** [comment]
@max-cx Please review https://github.com/redhat-documentation/supplementary-style-guide/pull/232 and provide feedback if you have any. Thanks!

**Comment by Srivaralakshmi** [comment]
@bergerhoffer and @bburt-rh I do not agree to add an entry or a generic admonition to avoid the word "project". PTAL at my [comment in the same attached](https://github.com/openshift/openshift-docs/pull/49201#discussion_r966092250) PR.

**Comment by bburt-rh** [comment]
> @bergerhoffer and @bburt-rh I do not agree to add an entry or a generic admonition to avoid the word "project". PTAL at my [comment in the same attached](https://github.com/openshift/openshift-docs/pull/49201#discussion_r966092250) PR.

@Srivaralakshmi I appreciate your concern and thank you for the feedback! My intention with this guidance is not to say that writers should avoid the word entirely, but rather the intent is to raise awareness that in certain situations using "project" (or other homographs) as both verb and noun in close proximity can potentially cause confusion. It's in these specific cases that writers should be aware of a potential issue and seek to work around them. 

If you have the time, could you PTAL at the PR I submitted and LMK whether or not this intention is expressed with enough clarity? https://github.com/redhat-documentation/supplementary-style-guide/pull/232 I'd love to hear your feedback! Thanks!
