### ISSUE TITLE
Man page references in "additional resources"

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/supplementary-style-guide#224]
Do we have a CCS-wide rule how to write man page references in "additional resources" sections?

* `sudoers(5)`
* `sudoers(5)` man page
* The `sudoers(5)` man page
* ...

Minimalists write only the man page name and chapter number. Other writers append "man page" to make clear what it is. However, at least for me, the latter feels incomplete without article. ...and we have more styles in our docs.

It seems we don't have an official rule yet. Let's discuss it and add the result to the RH SSG.

PS: The same question applies also to other references in "additional resources", for example for files: (`/etc/fstab`, `/etc/fstab` file, The /etc/fstab` file,...)

**Comment by bergerhoffer** [comment]
I don't have personal experience with referencing man pages in additional resources section, but I think that specifying "man page" is important. And that if you're going to have that, then the "the" in front makes sense. So my vote would be for the third option of:

* The `sudoers(5)` man page

**Comment by bburt-rh** [comment]
+1 to what @bergerhoffer  says. 

I think we should add this guidance (3rd option) to the SSG. There's nothing about man pages in the ISG, btw.

**Comment by mnsteven** [comment]
I also agree with @bergerhoffer, but that may well be because this is the style I used in previous companies.  The issue for me is using literals as nouns, so I also would do the same thing for files (the `/etc/lvm.conf` file).

This just came up in my release notes, where many of my headings refer to a feature of the `pcs` command-line interface.  So I had consistently used a title like "The pcs command-line interface now supports...".  All three of my peer reviewers said to use just "pcs" rather than "the pcs command-line interface".  It definitely makes for a shorter title, and I went with it, but I don't think it's correct -- although it doesn't bother me quite so much in a title as in a body of text.

**Comment by bergerhoffer** [comment]
So one thing I just thought of is that we had a similar issue opened a few months ago: #169. The IBM style guide (ISG) does provide some generic information on things like this (about specifying what the items is, "man page" in our case) after it. 

We didn't end up adding any guidance to the SSG for this raised issue, because the ISG provided ample guidance, and we don't duplicate guidance. I'm wondering if that can extend enough to cover your man page question here.

The examples given in the sections, do cover also including the "the". Though technically these are full sentences, which yours wasn't. From the ISG:

> Generally, when you specify the name of a command, parameter, or option in text, specify the word command, parameter, or option after the name.
> ...
> (incorrect) You can use db2trc to record information about operations.
> (correct) You can use the db2trc command to record information about operations. 

Let me know what you think!

**Comment by bredamc** [comment]
Here's my tuppenceworth:

**1. Re. include or exclude "man page"**
I think it depends on your target audience. Very technical readers would know that `sudoers(5)` is a reference to a man page, but I agree that we should standardise on including the text "man page", to cover all readers. 

**2. Re. include or exclude "The"**
I'd treat references to man pages in the same way as any other guide. If you would include an article before a title such as _Red Hat Enterprise Linux System Administrator’s Guide_, then include it before the man-page reference. So I'd vote for option 2 (no article) for a bullet list in the additional resources section, and option 3 (include article) for running text. 


**Examples:**

"
**Additional resources**
- _Red Hat Enterprise Linux System Administrator’s Guide_
- _Red Hat Enterprise Linux System Design Guide_
- `sudoers(5)` man page
"

"For more information about user authentication, see the `sudoers(5)` man page."

**Comment by mmuehlfeldRH** [comment]
I vote for the shortest version (`sudoers(5)`).

In the Linux/UNIX world, this format (a word with a number in parentheses) is well known as a reference to a man page. I think that only users who are absolutely new to Linux might not know this. I would also assume that this group of readers is really a very, very, small one, and they can easily find out elsewhere that `sudoers(5)` means a man page. We do not need to spell this out hundred times in one document (minimalism).

I think it's safe to assume such a tiny bit of preknowledge from our readers. I mean, even if we write "The `sudoers(5)` man page", we also automatically assume that the reader knows how to open a man page. :-)

**Comment by bergerhoffer** [comment]
I think @bredamc has a fair point about the "the" not being necessary. But I would rather err on the side of caution by still adding "man page" afterward, because `sudoers(5)` alone doesn't give the reader much to go on, especially if it's in the additional resources section and isn't a link. Though now that I think about it, I think the additional resources section (per the mod docs templates at least) are supposed to be links. (Side note to think about).

Maybe the `(5)` after `sudoers` is enough to tell people that it's a man page, but it isn't that obvious IMO. So I don't see any reason not to include "man page" after, since it will point people in the right direction if they're not familiar with that syntax. Probably the same reason why the ISG recommends specifying "command", "parameter", or "option" afterward as appropriate.

**Comment by bburt-rh** [comment]
I agree that @bredamc has a good argument for omitting the definite article.

I am also for including "man page" in the wording to stay consistent with the guidance about "command", "parameter", "option", etc in the ISG. One could argue, for instance, that experienced Linux/Unix users also do not need to be told that, say, `oc` is a command. But the ISG does say to specify "the `oc` command" anyway. So to stay consistent with the ISG, I think we should do the same when referring to man pages, My vote is for: 

- `sudoers(5)` man page

**Comment by mmuehlfeldRH** [comment]
> * _Red Hat Enterprise Linux System Administrator’s Guide_
> 
> * _Red Hat Enterprise Linux System Design Guide_

In these examples, "Guide" is part of the name of these guides. It's not describing what it is.

Most [RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8) and 9 titles start with a verb. Would you append "guide" to titles, such as:
* [Performing a standard RHEL 8 installation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation)
* [Upgrading from RHEL 7 to RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8)
* [Managing networking infrastructure services](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_networking_infrastructure_services)

**Comment by bergerhoffer** [comment]
@mmuehlfeldRH I'm not sure if we can make these comparisons here, because these are links. I might not care so much about the missing "man page" after "sudoers(5)" if it was an actual link that went somewhere / the name of a page that the link takes you to.

We're talking about something different here with sudoers(5), since it wouldn't be a link that takes the users to where they need to go. In this case, I think that the extra context that it's a man page is beneficial.

**Comment by JaroslavKlech** [comment]
I am kind of on the fence about this one. On one hand, I agree with @mmuehlfeldRH about `sudoers(5)` being a well-known term in the enterprise IT world (where our docs should be aiming at, and where vast majority of IT professionals know or should know this term).
On the other hand, @bburt-rh has a valid point about consistency with guidance about qualifying commands (the `yum` command), parameters, and even manual pages in other places other hand "Additional Resources".

**Comment by mjahoda** [comment]
+1 to https://github.com/redhat-documentation/supplementary-style-guide/issues/224#issuecomment-1255331992

**Comment by sbmetz** [comment]
Here's another thought (sorry I'm chiming in late) -- what do you think about an actual link, for example, [https://man7.org/linux/man-pages/man5/sudoers.5.html](https://man7.org/linux/man-pages/man5/sudoers.5.html)?

**Comment by mmuehlfeldRH** [comment]
> Here's another thought (sorry I'm chiming in late) -- what do you think about an actual link, for example, https://man7.org/linux/man-pages/man5/sudoers.5.html?

@sbmetz , I think it will be hard to maintain and only cause trouble.

You need to ensure that the HTML version of the man page you link is for RHEL. Not Fedora or any other distribution, because it can be different. Even if hosted on redhat.com and we are sure that it's for RHEL, we would need HTML versions of every man page for each RHEL version. RHEL guides are valid only for the latest minor version, but also in this case, we would need at least an HTML version of every man page for 7.9, 8.6, and 9.0.

Let's better rely on the man page users have on their system. It is always automatically valid for the RHEL version they run.

**Comment by mportman12** [comment]
Style Council meeting outcome: Recommend “sudoers(5) man page”. @bergerhoffer to follow up in the issue.

**Comment by bredamc** [comment]
I think we should list each man page in a separate bullet, similar to how we list multiple guides.

Perhaps we could create a general module to explain common info about man pages:
- What is a _man page_
- How to run the `man` command to display a man page
- A command name can be reused in multiple categories, so you should include the specified category in the `man` command,  to make sure that you're viewing the correct man page.
- Man pages are specific to a particular operating system and version, so you should view the man page on the target system.

And then we could link to that explanatory module whenever we refer to a man page?

**Comment by mportman12** [comment]
Discussed at February 22 Style Guide meeting. We decided to Table bullet point discussion until Mod Docs can discuss. Common content page would be beyond scope and probably not needed for our audience.

**Comment by Srivaralakshmi** [comment]
Any progress on this?

**Comment by Srivaralakshmi** [comment]
Any progress on this? Please respond.

**Comment by mportman12** [comment]
@emmurphy1 any progress on this?

**Comment by mportman12** [comment]
@bergerhoffer Can you update the PR?

**Comment by bburt-rh** [comment]
@bergerhoffer Where are we with the PR for this issue? Thanks!

**Comment by Srivaralakshmi** [comment]
@bergerhoffer Where are we with the PR for this issue? Thanks!
