### ISSUE TITLE
Replaceable value recommendation for XML

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/supplementary-style-guide#25]
The general replaceable value format that we are recommending is this: _<ip_address>_.

However, that is not XML-friendly due to the angle brackets (`< >`). Investigate an alternative format to recommend when using replaceable values in XML.

* Should the recommendation be just to remove the angle brackets? _ip_address_
* Or is there another format that is commonly used that we should recommend?

**Comment by inoxx03** [comment]
In Cloud-Native runtimes we use a form of notation that is based on Maven configuration files (such as pom.xml). You can see one instance of this usage in the first code example in section 4.3.1 of the Red Hat support for Spring Boot runtime Guide.

The syntax is `${property-name.type}`. 

The `type` is usually `version`, although there might be other property types.

Since this notation is compatible with the way you reference external properties in actual POM files, this notation carries the added benefit that it can be copied and pasted to a POM file of another Maven project that is based on Spring Boot:

Example:

```xml
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-web</artifactId>
<version>${spring-boot.version}</version>
</dependency>
```

@bergerhoffer I'm not sure how well this would work for XML examples that are not centered around Maven and Java, but I think this notation is quite clear and easy to recognize. We could also italicize it, although that might be excessive.
Please let me know what you think.

**Comment by leswilliams44** [comment]
@bergerhoffer  and @cbudz , Any suggestions on how to move this forward? Are we waiting for a group decision during a regularly scheduled meeting?

**Comment by bergerhoffer** [comment]
@inoxx03 Thanks for adding this, this is helpful! My question to you is whether this value is something that we expect a user to manually replace before using this XML example, or is it something that we expect them to have the `spring-boot.version` field set somewhere else, and they leave that variable in there? It looks like it might be the latter.

Also, as you mention, this might not necessarily work for XML snippets that aren't using Maven/Java.

@redhat-documentation/ccs-style-council does anyone else use XML code snippets in their product's docs that has any examples of using replaceable values in XML code?

**Comment by leswilliams44** [comment]
Hi, @bergerhoffer, Are there any updates for this issue?

**Comment by bergerhoffer** [comment]
I don't have any updates because we don't really use XML on OpenShift so I'm not sure what a good recommendation would be. I'll add this to next meeting's agenda.

**Comment by sterobin** [comment]
@bergerhoffer @leswilliams44 Well, in our product we use XML variables a lot and we used to use what @inoxx03 mentioned because that's the standard in Maven pom.xml's anyway and commonly adopted. However, I went through and updated all of those refs to __IP_ADDRESS__ (as an example), no brackets, ital, and all caps, because that was the initial decision we made. I noticed we decided against that but then I wasn't able to go back and re-change that yet. So if we are going with that bracket version, then I vote @inoxx03 example as the XML format.

**Comment by bergerhoffer** [comment]
As discussed in the meeting today, @sterobin mentioned that the ${} format was what people would expect to look for, no matter whether it's a system-replaced value, or a user-replaced value.

And that as long as we italicize the options that the user has to actually replace, that should be a good enough differentiation.

**Comment by bergerhoffer** [comment]
Will open a PR to add that note, so that others can weigh in/see if there are any concerns.

**Comment by sterobin** [comment]
Also as discussed in the meeting, the only downside of the ${} format is that relying on lowercase ital as the indicator for user-replace vs. system-replace (no ital) is pretty subtle and could leave users wondering if it's an error or intentional. This was one of the upsides of going the all-caps route that we initially discussed many moons ago. But we have to move forward with something, and the list of cons will always be there for whichever route, so I guess we'll give this a whirl and see how it goes. Good news is that it's at least slightly more in line with IBM anyway (lowercase ital). Thanks @bergerhoffer .

**Comment by bergerhoffer** [comment]
This is on me to submit a PR for.

**Comment by dfitzmau** [comment]
Separate PR raised for the ${} suggestion for code bases that use angle brackets to enclose their elements:

https://github.com/redhat-documentation/supplementary-style-guide/issues/94

**Comment by bergerhoffer** [comment]
Opened #95 to add the entry. The only thing I wasn't super sure about was making sure that still using underscores as the separator for multi-words was appropriate.

**Comment by bergerhoffer** [comment]
Closing because the PR has merged. Update is live: https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values-xml
