### ISSUE TITLE
Review Red Hat style & mod doc guidance on using gerund verb form in titles of procedures

### ISSUE THREAD

**Issue by michelle-purcell** [redhat-documentation/supplementary-style-guide#256]
Do we have the blessing of the Red Hat supplementary style council to completely drop gerunds in procedures and how-to topics?

**Why are we asking?**

The Quarkus docs team is moving to an upstream-first approach to developing product content. The upstream community content uses the [Diátaxis](https://diataxis.fr/explanation/) framework for defining content types. In this framework, a Red Hat modularized procedure is closely mapped to a ‘how-to’ or a ‘tutorials’ topic.  Both Diátaxis and the Quarkus style prefer the imperative verb form. They dislike and reject the guideline to use a gerund as the first word in the title of a procedure.

If Quarkus docs continue to align with Red Hat style and use gerunds as the first word in procedures in the product documentation, an effort will be required to ‘convert’ our titles from imperative verb form to gerunds. For example, we could use attributes to render bare infinitives upstream and gerunds downstream. This is not scalable or the best use of our time. 

Overusing attributes adds complexity and in doing so we risk frightening off potential contributors who want to make a high-value update for technical accuracy.

More importantly, we do not believe that gerunds improve findability, usability, or the overall customer experience.

**Arguments against using gerunds:**
- Gerunds can be "ambiguous" because sometimes the reader can interpret the gerund as a noun, verb, or adjective.
- Gerund forms are inconsistently translated when they're used as the first word in a title. 
- Gerunds increase character count in limited spaces, especially ToCs.
- The [Diátaxis](https://diataxis.fr/) guidelines suggest gerund form is ambiguous and confusing.
- Encourages a consistent user experience for Quarkus readers that switch from upstream to downstream.
- SEO: Users don’t typically use the “ing” in their search queries. They use imperative verb form like "install", "configure", or "authenticate".
- SEO: Search engines include the “ing” as an alias and can find content without the “ing” in the search string. 
- IBM Style guidelines state:
 **_“Use either a gerund or an imperative verb form for the subtasks of a high-level task.”
The option to use either a gerund or the imperative form for subtasks can also lead to inconsistency/ambiguity depending on whether the writer decides if the task is mandatory or "not necessarily mandatory"._**
- Other well-known style guidelines advise against using the gerund form, for example, google developer style ⬇️ and popular technical writing articles.

**Arguments for using gerunds**
- Not as forceful and ideal for tasks that are not mandatory.
- Because all of our other docs use them.
- Because our style guide tells us to.

Can we revisit our guidelines and encourage using the imperative verb form instead of a gerund as the first word in a procedure or how-to topic?

**Research points:**

- [The Red Hat supplementary style guide](https://redhat-documentation.github.io/supplementary-style-guide/) for product documentation does not mention any guidance about using gerunds.

- The [Wording section of the Headings guidelines](https://www.ibm.com/docs/en/ibm-style?topic=format-headings) in the IBM style guide states:

  **_For a task procedure heading, use a gerund or imperative verb form. Use a gerund for a high-level task such as installing, administering, or troubleshooting. Use either a gerund or an imperative verb form for the subtasks of a high-level task. A gerund implies that a task is not necessarily mandatory, but rather that the task applies only if it is what the reader wants to do (for example, "Deleting obsolete entries"). The imperative voice is more prescriptive and implies that a step is mandatory (for example, "Ensure that prerequisite software is installed"). The imperative voice is also preferable for subtask headings that are used to create a list of steps in what is a larger procedure, such as a series of installation steps._**

- The [Red Hat modularization guidelines](https://redhat-documentation.github.io/modular-docs/#con-creating-procedure-modules_writing-mod-docs) suggest that the title of a procedure module is a gerund phrase:
![image](https://user-images.githubusercontent.com/92924207/201975089-fa1978b7-e010-42f1-b3d8-822b46a55795.png)

- The [google developer documentation](https://developers.google.com/style/headings) style guide advises: when possible, avoid using -ing verb forms as the first word in any heading or title.

  - An -ing verb form is a present participle or gerund. These verb forms are inconsistently translated when they're used as the first word in a title, and they increase character count in limited spaces.
![image](https://user-images.githubusercontent.com/92924207/201980162-861d109e-bcd5-47c9-8537-fded5dc72b63.png)

- [Write the Docs](https://www.writethedocs.org/blog/newsletter-october-2022/#gerunds-in-headings) makes the point that gerunds …
  - Introduce a lot of visual repetition, which hinders skimming and causes noise.
  - Are inconsistent with how people browse the internet. 
  - Can be challenging to translate and localize since some languages do not have identical counterparts.

- Tom Johnson from [I’d rather be writing](https://idratherbewriting.com/2008/02/11/are-gerunds-in-topic-titles-problematic-in-search-results/) said he is thinking of saying goodbye to gerunds in topic titles.

**References:**

- https://www.writethedocs.org/blog/newsletter-october-2022/#gerunds-in-headings
- https://idratherbewriting.com/2008/02/11/are-gerunds-in-topic-titles-problematic-in-search-results/
- https://redhat-documentation.github.io/supplementary-style-guide/
- https://www.ibm.com/docs/en/ibm_style/headings.html
- https://redhat-documentation.github.io/modular-docs/#con-creating-procedure-modules_writing-mod-docs
- https://developers.google.com/style/headings

**Comment by rolfedh** [comment]
As a technical writer, our training makes it difficult to overcome our biases and objectively consider this proposal.
The first step might be to talk about the _bare infinitive_ instead of the _imperative_ form of a verb. For example:
![image](https://user-images.githubusercontent.com/350907/202019452-a74b9d64-53c9-4d23-89af-6936056e4158.png)

**Comment by rolfedh** [comment]
As a technical writer, I had some initial biases that made it hard to consider this alternative objectively.

For me, the first step was to think of this verb form as the _bare infinitive_ instead of the _imperative_.  Both have the same appearance but serve different purposes. 

The Google [developer documentation style guide](https://developers.google.com/style/headings)] explains:
![image](https://user-images.githubusercontent.com/350907/202019452-a74b9d64-53c9-4d23-89af-6936056e4158.png)

Now, read the following title:

## Create a rock garden

Does this title sound like a command or an invitation? I think, now, it might sound like an invitation to you. 
If I saw this title, I would expect the following content to include a short description informing me of the ease and benefits of creating one. The user always decides whether to do something based on their context and the information you furnish.

**Comment by bergerhoffer** [comment]
@michelle-purcell thanks for opening this issue!

As it stands now, the modular docs templates state that the headings for procedure modules should start with a gerund (which you are already aware of since you quoted this item in the procedure module template [1]):

> Start the title of a procedure module with a gerund, such as Creating, Installing, or Deploying.

As that stands right now, that is the rule that all teams creating product docs should be following. That is a decision that came from the modular docs team and is not something that the SSG would be able to change. We work side-by-side with the mod docs guide and try not to do anything that conflicts with their guidance or rules.

I recommend opening this question as an issue against their project: https://github.com/redhat-documentation/modular-docs/issues. They could likely give more insight into why a gerund was chosen for the template, and might be able to give some other guidance as well.

I personally prefer titles that start with gerunds, and it stands out to me pretty harshly when I see someone accidentally forget to use one in a module heading. So I would not want to see a mix and match of imperative and gerunds in the same doc set. 

However. I don't know if we say this anywhere, but I think we all expect that different projects might have certain things that they need to add on to or deviate from our normal guidance on for one reason or another. I don't want to encourage diverging for no good reason, but I think if it comes down to a good business or technical reason, and you've discussed it with your CS/DPM, etc., then it might be fine to. I'm not positive if this is one that fits that bill or if we really should enforce it, but I'll just leave that there for thought.

You might want to also consider reaching out to other teams that single source upstream/downstream and see how they handle any variations in style between the two.

Hope that helps some at least!

[1] https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_PROCEDURE_doing-one-procedure.adoc

**Comment by michelle-purcell** [comment]
Thanks @rolfedh - & +1 :+1:

**Comment by michelle-purcell** [comment]
Thank you @bergerhoffer for your prompt review and feedback on this :+1: 

I opened an issue with the mod-docs team here: https://github.com/redhat-documentation/modular-docs/issues/199

**Comment by rolfedh** [comment]
If Emily or the Mod Docs council concurrs, and based on @bergerhoffer's comments above, perhaps we could add something like the following note to the SSG:

```
## Using bare infinitives instead of gerunds in titles

In some cases, such as in an upstream-downstream doc set where the upstream community requires them, 
you can use bare infinitives in all titles instead of gerunds.

Avoid bare infinitives in titles in the following cases:
- When they are not required by the upstream community.
- When it is likely that modules from this doc will be re-used alongside modules from other doc sets that do not use bare infinitives in titles.
```
-

**Comment by bergerhoffer** [comment]
From the SSG side, I would be less likely to want to add the first option (about allowing anything other than gerunds for procedures), because again, this rule is defined in the mod docs templates. Any exceptions to that rule should be documented in the template/mod docs guide, not the SSG.

It's true that the mod docs guide does use the SSG/ISG, but neither of those say to use only gerunds. So afaik it was the mod docs group who decided to make the rule to confine only to gerunds - so that's why it's them that should decide whether to officially allow anything else in the template.

I'm open to adding the "exceptions" section you mention, but would definitely want to think about it more and get more thoughts from other @redhat-documentation/ccs-style-council members before committing to that. Thoughts anyone?

**Comment by emmurphy1** [comment]
Here is what I posted in the mod docs issue:

The question is consistency and scannability. The decision to use gerunds in procedure titles predates my involvement with the modular documentation project.  However, I imagine at the time these decision were made different options were proposed and voted on. While I personally do not have a strong preference for gerund phrases over imperative statements for procedure module titles, I do have strong reservations about changing the directive. If we do that, do we change all of the existing procedure module titles?  Highly unlikey. So then do authors then decide for themselves to use one or the other, or just new procedure modules use imperative titles? Doing this will introduce inconsistency through our documentation and make documents harder to scan.

**Comment by rolfedh** [comment]
Thank you, Emily. 

The use case for this issue might be unclear. It is to update the SSG so that a specific doc set (Quarkus) can adopt the upstream community practices (bare infinitives) rather than shoehorn a solution that uses gerunds in titles. The request is _not_ to mix titles with bare infinitives and gerunds in a single doc set. That _would_ be confusing.

Rather than making a specific exception for this case, the current discussion seems to favor a guideline about making exceptions to Red Hat's style guidelines.

**Comment by bburt-rh** [comment]
I would be in favor of changing our guidance to allow some flexibility around this issue in specific and well-defined circumstances -- maybe guidance along the lines of what @rolfedh suggested earlier in this thread. 

It's a big enough change where I think we'll want to be very cautious and limiting in what we allow and when we allow it -- maybe even to the point of stating that exceptions can only be granted by the Mod Docs group or by the Style Council on a case-by-case basis and only for new doc sets. 

I'd prefer not to see us put ourselves in a situation in which there is overall inconsistency across the doc sets, and most of our doc sets do it one way, whereas a significant minority of other doc sets do it another way.

**Comment by bburt-rh** [comment]
I agree that we don't need a "style police force" :+1: , but what's the best way to strike a balance between inflexible rules and reasonable exceptions to those rules? At what level should the decision about what's a "reasonable" exception be made? Project level? Maybe if we add any guidance at all to the SSG, it should be to specify a) that project/product teams can agree on exceptions to specific SSG or IBM Style guidance, and b) to maintain consistency across doc sets, these exceptions should be a rarity. Or something like that.

**Comment by mportman12** [comment]
Current status: Andrea and I discussed with Emily and Jana from Mod Docs and have scheduled a meeting to discuss further with the Quarkus team to better understand why they want this change and how their documentation is affected.

**Comment by inoxx03** [comment]
After discussing this issue at our latest CCS Style Council meeting, the I met with our writers on Quarkus docs  and we re-evaluated our proposal to formalize the use of infinitive-form action verbs in procedure titles as an alternative to the currently recommended use of gerunds. We have decided to postpone our proposal to formalize this practice in both the SSG and the Red Hat Modular Documentation guidelines indefinitely.

For the time being Quarkus docs will continue to use gerunds in procedure titles, in what  the CCS Style Council has deemed to be an acceptable deviation from guidance currently given by the SSG (Note, that even though this is a deviation from practice recommended by the SSG, the use of infinitives in procedure titles is still endorsed by the IBM Style Guide).

We are open to revisiting our proposal if we ever need to formalize this practice in the future.

@bergerhoffer I am closing this issue.

Thank you.
