### ISSUE TITLE
Add guideline for links to Red Hat Knowledgebase articles

### ISSUE THREAD

**Issue by stoobie** [redhat-documentation/supplementary-style-guide#29]
Problem: Links to Red Hat Knowledgebase articles don't always follow normal link guidelines.

For example:

- `For more information, see the Knowledgebase article at https://access.redhat.com/solutions/163853.` [1]
- `If your Apache web server configuration enables SSL security, verify that you enable only the TLSv1 protocol, and disable SSLv2 and SSLv3. This is due to the POODLE SSL vulnerability (CVE-2014-3566). See https://access.redhat.com/solutions/1232413 for details. `[2]
- `For a non-cloud environment, the disk and file system can be resized. See the following solution for more information: https://access.redhat.com/solutions/199573`[3]

[1] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#manual-partitioning_graphical-installation
[2] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_a_standard_rhel_installation/index#creating-an-installation-source-on-http_prepare-installation-source
[3] https://docs.openshift.com/container-platform/3.9/day_two_guide/docker_tasks.html

**Comment by bergerhoffer** [comment]
+1 for adding guidance on this.

I don't think that we want to just show the URL as the link like any of these options show.

I would rather see the link text be the title of the Knowledgebase article/solution, or linked as running text:

#### Title:

`For a non-cloud environment, the disk and file system can be resized. See the following Red Hat Knowledgebase solution for more information: link:https://access.redhat.com/solutions/199573[Does RHEL 7 support online resize of disk partitions?].`

_Rendered_:
For a non-cloud environment, the disk and file system can be resized. See the following Red Hat Knowledgebase solution for more information: [Does RHEL 7 support online resize of disk partitions?](https://access.redhat.com/solutions/199573)

#### Running text:

`If your Apache web server configuration enables SSL security, verify that you enable only the TLSv1 protocol, and disable SSLv2 and SSLv3. This is due to the link:https://access.redhat.com/solutions/1232413[POODLE SSL vulnerability (CVE-2014-3566)].`

_Rendered_:
My question would be whether or not we want to recommend to call out that this is a Knowledgebase article/solution in the text. For example:

**Comment by bergerhoffer** [comment]
I've also seen links where the link text says "this Red Hat Solution". We should probably state to avoid that, in addition to avoiding just using the URL.

**Comment by stoobie** [comment]
@bergerhoffer Thanks for the great suggestions. I'll take your comments into account in the PR. I created a new branch, but didn't get a chance to push it yesterday. Will do so today.

**Comment by stoobie** [comment]
This issue was addressed in https://github.com/redhat-documentation/supplementary-style-guide/pull/33, so I'm closing this issue.
