### ISSUE TITLE
Variable text and highlighting of text fragments in output of commands

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/supplementary-style-guide#303]
The Supplementary Stlye Guide provides [guidance on user-replaced values](https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values) in commands, but what about their output? Should values, that are different on the reader's system, have markup (italic) to make clear that they are different?

**Example 1:**

Display the connection profile to verify the settings of the Ethernet connection:
```
# *nmcli connection show __<profile_name>__*
connection.id:              __profile_name__
connection.uuid:            _b6cdfa1c-e4ad-46e5-af8b-a75f06b79f76_
connection.type:            802-3-ethernet
connection.interface-name:  _enp7s0_
...
```

To make clear that the values next to id, uuid, and interface name can be different on the reader's system, I would use italic for them. I would not use <> with descriptions (e. g. <interface_name>) in output. It would make it hard for the reader to compare.

**Example 2:**

Display the RX error counter of the `enp10s0u1` interface:
```
# *ip -s link show _enp10s0u1_*
...
RX: bytes         packets    errors  dropped  missed   mcast           
    _5113773431_  _3662459_  _50_    _33238_  _0_      _0_
...
```

This 2nd example also brings up the question whether we can use bold (**) in the output to highlight things the user should search for (**50**). We use bold for the command (user input), which could make bold text in the output look like something the user should enter as well.

**Comment by bergerhoffer** [comment]
@mmuehlfeldRH The guidance on replaceable values in the SSG isn't just limited to commands.

> A _user-replaced value_, also known as a replaceable or variable value, is a value that the user must replace with a value that is relevant for their situation. User-replaced values are often found in places such as **code blocks, file paths, and commands**.

So this would mean that if you're showing values in the output that are also replaceable, then they should use the same italics and angle brackets as anywhere else.

**Comment by mmuehlfeldRH** [comment]
@bergerhoffer , in the examples in the ticket description above, I used only italic for the replaceable values in the output. The following are the same examples, but with the SSR rules applied:

**Example 1:**

Display the connection profile to verify the settings of the Ethernet connection:

```
# *nmcli connection show __<profile_name>__*
connection.id:              _<profile_name>_
connection.uuid:            _<uuid>_
connection.type:            802-3-ethernet
connection.interface-name:  _<interface_name>_
```

**Example 2:**

Display the RX error counter of the enp10s0u1 interface:

```
# *ip -s link show _enp10s0u1_*
...
RX: bytes         packets            errors         dropped             missed                  mcast           
    _<rx_bytes>_  _<total_packets>_  _<errors>_    _<dropped_packets>_  _<missed_packets>_      _<multicast_packets>_
...

```
To me (as reader and former admin), this output in verification steps is is less helpful: It's much harder to read, more difficult to compare with the output on the own system, and it somehow looks ridiculous :-) 

For replaceable values in output, I think it makes more sense to use only italic.

**Comment by mmuehlfeldRH** [comment]
I only show (partial) output of commands when it helps the reader or if needed in the rest of the procedure. This style question affects many of my procedures.

Here's another example: [Increasing the ring buffers to reduce a high packet drop rate](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/increasing-the-ring-buffers-to-reduce-a-high-packet-drop-rate_configuring-and-managing-networking#doc-wrapper)

The values in the output of step 1 and 2 will all be different on the reader's system, but it's important to show them (otherwise, showing only the command would be sufficient).

This is how it looks in a direct comparison:
![example](https://user-images.githubusercontent.com/43061675/227140545-0da8574d-e30e-4c81-8aa9-2f557ac2092d.png)

In the version on the right side, I would probably drop the output, because it is no longer helpful. Anyway, in this version, the user needs to figure out more things on its own, which are obvious in the version on the left side.

**Comment by jafiala** [comment]
@bergerhoffer I had discussed this with Mark during a PR. I think the issue is that we don't have clear guidance for values that the user does not have to replace, but which will or might differ on the user's system (typically in output). I think the use of italics is reasonable because it indicates these values might differ, but does show the general format.

**Comment by bergerhoffer** [comment]
So I'm going to reply to two angles of this: 

1. whether to indicate values that might be different on a user's system 
2. how to show replaceable values in example output

For 1:

So IMO I don't think you have to indicate every single value in example output that might be different on someone else's system.

At least the way we do things on OpenShift, we always separate the command block from the output block. And we use a title of "Example output" above the output. This helps to show that the output is just an example and might not exactly match the user's output.

So that means that sometimes we show just example values in the output. We don't mark those up in any special way. I do think that showing an example value is more useful in the output than showing just <value>, as you pointed out. But I don't think you'd need to italicize that value just because it might be different than what the user sees. 

Indicating a replaceable value is definitely more important in code/commands that the user has to change before issuing the command/submitting the code than it is in example output. 

For 2:

If I did have an instance where I have a command w/ a replaceable value and then example output that includes that value, I would approach it one of the following ways:

* Use the replaceable value both in the command and output, and mark them up the same way (italics and angle brackets) both places
* Use the replaceable value in the command, but then give an actual of the command and corresponding output using an example value.  But don't mark up that example value any differently.

So my point here is that I would either use a replaceable value with our recommended format, or just use an example value with no special formatting. You always have the option of explaining with callouts, etc. if it's necessary to make users aware of differences that they might see. We don't really use italics that way right now.

Interested to hear what others on the council think on this.

**Comment by mportman12** [comment]
Discussed at March Style Council session. The council agreed with Andrea that replaceable values should only be formatted in outputs if it adds value to the customer or if the replaceable value was also in the command, otherwise values should be unformatted. If formatted, council agreed with Andrea to use italics and angle brackets as we do for values in commands.
The current guidance in the SSG does not mention unformatted replaceable values in output examples. Does anyone on @redhat-documentation/ccs-style-council want to take a PR to add that?

**Comment by mportman12** [comment]
[PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/310)
