### ISSUE TITLE
Ansible Playbooks capitalization

### ISSUE THREAD

**Issue by catontoast** [redhat-documentation/supplementary-style-guide#312]
Per our corporate style guide, we use "Ansible Playbooks" but "playbooks" when not preceeded by Ansible. (Ditto for "Ansible Roles"/"roles", etc.) Can the relevant entries be updated to align with this guidance? The disparity is causing confusion for some writers/content stakeholders.

https://redhat-documentation.github.io/supplementary-style-guide/#_a

**Comment by mportman12** [comment]
RHEL IdM uses "Ansible playbooks", uncapitalized. Possibly this is in error. I did a quick search of Ansible docs and found instances of both "Ansible Playbooks" and "Ansible playbooks". Does anyone have particular knowledge of how this term is spelled on the Ansible side?

**Comment by IngridT1** [comment]
@mportman12, @lburcher7 and I brought this issue up at Word Nerds, so may not have to wait for Lorena to return to finish up with tis issue. 

Our description of the problem:

> The official Product names list says to capitalize "Ansible Playbooks" but not "playbooks" by itself. However, Ansible Playbooks is not a product, so playbooks should be lowercase. Can we change the guidance?  It's very confusing to go from: [What is an Ansible Playbook?](https://www.redhat.com/en/topics/automation/what-is-an-ansible-playbook) to the [Lab](https://www.redhat.com/interactive-labs/write-your-first-playbook) that you can launch from this page. In the lab "playbook" is always lowercase.

Word Nerds' answer:

> This is probably a convo best had with Kristin Andrews and the naming teams. "Ansible Playbooks" is grandfathered in from Ansible's acquisition. Katrina is also working with GitHub and docs about how this is implemented. This one probably goes to Naming but we can follow and report back. So at this point we've asked @catontoast to pursue this with Naming and Kristin Andrews.

**Comment by mportman12** [comment]
@IngridT1 Thanks for following up on this!

**Comment by bredamc** [comment]
@catontoast Can you please provide an update on this issue? Do we have a definitive answer about whether we should refer to "Ansible Playbooks" or "Ansible playbooks"?

**Comment by IngridT1** [comment]
Honestly, @bredamc, it seems like it should be "Ansible Playbooks" based on its having been grandfathered in as part of the Ansible acquisition. We should just leave it alone, I think. We could have a "playbook" entry in the glossary if we want to be super clear. If we don't hear back from @catontoast, that would be my advice.

**Comment by bredamc** [comment]
@IngridT1 As far as I could see, the UI text (at the Lab link mentioned above) is also following the guidance from the official products list -- "playbook" is all lowercase because it is not preceded by "Ansible".  


I think we need to update the usage in the SSG to obey the guidance in the official product names list, as follows:

1. General: Update all occurrences of "Ansible playbook" (throughout the SSG) to "Ansible Playbook".

2. "Ansible Playbook" entry: Add the following sentence and examples:
'
    When "Ansible" does not precede "playbook", then "playbook" is not capitalized. 
    
     Examples: 
       - _Run an Ansible Playbook._
       - _Run a playbook in Ansible._
'

3. "Ansible Playbook" entry: Add "Ansible playbook" to the "Incorrect forms" section.


I don't think we need a separate entry for "playbook'; it's covered by the proposed new sentence in point 2 above? 

WDYT?

**Comment by IngridT1** [comment]
That looks good, @bredamc 

Luckily, it is not in the SSG at all.
