### ISSUE TITLE
Official synonym for command line argument/parameter/option

### ISSUE THREAD

**Issue by bscott-rh** [redhat-documentation/supplementary-style-guide#313]
```
Use the `-n NAMESPACE` option to specify a...
```
the style guide does not describe an official synonym for "option" in the above example. Different choices include "argument", "parameter", "flag" or "switch". What is the preferred term for this case?

**Comment by mportman12** [comment]
RHEL overwhelmingly uses "option". Is there any reason why you would want to use a synonym instead?

**Comment by bergerhoffer** [comment]
I think that this would be difficult to make an entry for. I see these used very interchangeably across a lot of places (not just our docs). And it could be different in some contexts.

That being said, I think that "option" is the most universal/best one to go with. It's generic enough and well understood. Some of the others could be interpreted differently (like flag could mean an option that takes no argument, argument is the actual value you pass into the flag, switch could again mean just on or off). 

Plus in your example here, I'm assuming you're quoting something from OpenShift, and if you look in the help for the CLI, it lists them as "options".

For example:
```
[ahoffer@ahoffer ~] $ oc login --help
Log in to your server and save login for subsequent use.

...


Options:
    -p, --password='':
	Password for server

    -u, --username='':
	Username for server
    --certificate-authority='':
	Path to a cert file for the certificate authority

    --insecure-skip-tls-verify=false:
	If true, the server's certificate will not be checked for validity. This will make your HTTPS connections
	insecure

    --token='':
	Bearer token for authentication to the API server

...
```
So that's what I'd recommend at least for OpenShift. But again, I'm hesitant to move forward with an entry on this, but am curious what others think.

**Comment by bredamc** [comment]
@bscott-rh Can you please clarify the intent of this issue? 

1. Do you want to use a synonym instead of _option_ ? If so, why?
2. Are you asking us to document all of the terms ("argument", "flag", "option", "parameter", "switch"), with advice about when to use (or not use) each term?

**Comment by bscott-rh** [comment]
@bredamc Sorry for the delayed response. This discussion came up during a peer review where a writer was asking if a more specific word could be used than "option". Based on the comments here, I'm happy to continue using "option". Thanks
