### ISSUE TITLE
Correct spelling and capitalization for "sosreport"?

### ISSUE THREAD

**Issue by IngridT1** [redhat-documentation/supplementary-style-guide#315]
At this point, I've seen the following spellings:

- sosreport
- sos report
- SOSREPORT
- SOS REPORT

@mportman12 has also seen "SOS report", although she thinks that "sosreport" is the most common. We need to standardize. The command to generate a report is `sosreport`

**Comment by bergerhoffer** [comment]
I don't know the answer to this one, but I will say that I always thought it was `sosreport`. However, in just trying it out, running `sosreport --help` gives me the following message:

```
Please note the 'sosreport' command has been deprecated in favor of the new 'sos' command, E.G. 'sos report'.
```

So the `sosreport` command is actually deprecated in favor of the `sos` command. Again, I don't know what to do with that information, just sharing :slightly_smiling_face: 

But IMO I still think that "sosreport" is probably most common. "sos report" is probably the other valid option though. However, looking at the help for "sos" it does still use "sosreport" and doesn't use any sort of "SOS" capitalization, so I'd probably at least stay away from anything with a capital "SOS". 

Based on ^, "sosreport" would be my recommendation, but I don't work with them in my daily writing, so I'm not the best person to weigh in here. @redhat-documentation/ccs-style-council any other opinions here?

**Comment by bredamc** [comment]
I'd never heard of this term or command so I'm not the best person to answer either, but I tried a few "man" commands to check the output:

In the "man sosreport" command output, the NAME and SYNOPSIS sections both refer to "sos report". The output does contain some refererences to "sosreport", but I imagine these references might have been missed when the command was renamed:
"... the resulting archive that sosreport produces ..."
"... the user running sosreport must match ..."
"... if sudo is used to run sosreport ..."
"... the number of threads sosreport will use ..."
"... Causes sosreport to leave an ..."
"... to prevent sosreport working dir ..."
"... The sosreport archive will still remain ..."


The "man sos" command output includes the following sentence:
"The most well known function is **sos report** or **sosreport** as it was previously known."
[sos report] "May also be invoked via the alias rep or the deprecated command sosreport."

The "man sos" output also contains other references to "sosreport", which perhaps should have been updated --  the same references as the first four references listed above for the "man sosreport" command, and the following text for the "clean|cleaner|mask" subcommand:
"This subcommand takes input of either 1) an sosreport tarball, 2) a collection of sosreport tarballs such as from collect, or 3) the unpackaged directory of an sosreport and obfuscates..."


If we decide to add an entry to the SSG, I'd vote for creating an entry for "sos report" as the preferred term (and mention that the term "sosreport" is now deprecated), and list the uppercase variants as "Do not use". 
But we should definitely check with an SME first :)

**Comment by IngridT1** [comment]
Who do you think we should contact in Support about this? Maybe Molly Kepley?

**Comment by TurboTurtle** [comment]
Hi all,

I'm the lead developer/maintainer for sos, so let me break this down a bit as it has actually changed over time somewhat.

The _project_ has always been "sos". This is actually an acronym for "son of sysreport", which was the predecessor to the current python project. This is generally where the capitalized version of "SOS" comes from, though it's not something we as the developers have ever used officially.

Originally, and for many years, sos had one utility, that being to generate a "report" of the system it's run on so that support engineers can review system data without needing to directly access the host.

During this time, the CLI command was `sosreport`. The package on RHEL and RHEL derivates was always called `sos` to reflect the name of the project, however some other distributions which use and contribute to the project name(d) their package `sosreport` to mimic the command.

As of a few years ago however, we re-designed the project to provide more than just the "report" functionality and along with that we renamed the command used to just `sos`, thus the `sosreport` command became `sos report`, and newer commands like `sos clean` and `sos collect` have been added.

There is a little over a decade of previous usage of `sosreport` as the command however, which is why our documentation is mixed.  At the end of the day, the project is named `sos`, and the command is `sos` and I personally have been pushing for documentation like KCS to use `sos` as the one and only reference. To that point, I would like to stress that this is officially pronounced "ess-oh-ess" and not "sauce" (which is how many people colloquially say it), and so grammatically it should be "an sos ....", not "a sos...".

**Comment by bredamc** [comment]
Proposed draft in PR #327.

**Comment by mportman12** [comment]
Report from Steven Levine: 
Followup to your polling question about the pronunciation of "sosreports" and oh yeah, I see what you meant about there being a controversial history here (is "controversial" the word you used?  something like that).  I had said I'd ask at my bi-weekly sbr-hacluster team meeting -- which is only 5 people so even as a sample it's limited.
So first off, I was correct that all of the support engineers use what we called out as "sauce reports".  BUT one of the engineers said that in his previous group the developer responsible for maintaining  SOS had once come to his group to tell them specifically that this is not correct, that they should be using "ess-oh-ess reports".  The other support engineers said they hadn't known that, and thought that was interesting.  It's as if this had become a cultural meme, to pronounce it "sauce", that had spread.
The conclusion is what I think you already knew:  The support engineers say "sauce reports" but some of them say this even knowing this is not "correct".  For what it's worth, they see no problem with our style standards using the "correct" pronunciation (and thus an sosreport).
Not helpful, I know, but it was an interesting five minutes at the meeting.
