### ISSUE TITLE
Format of buttons and key names

### ISSUE THREAD

**Issue by mmuehlfeldRH** [redhat-documentation/supplementary-style-guide#320]
The Red Hat Customer Portal renders the AsciiDoc `btn:[]` ([Button Macro](https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/)) and `kbd:[]` ([Keyboard Macro](https://docs.asciidoctor.org/asciidoc/latest/macros/keyboard-macro/))  in a specific style.

Example:

Source code:
`Select btn:[OK], and press kbd:[Enter].`

Rendering on the Red Hat Customer Portal:
![screenshot](https://github.com/redhat-documentation/supplementary-style-guide/assets/43061675/8f7f9db1-bd6e-4850-976e-067fa03dca20)

That's what I found in our style guides:

- IBM Style Guide ("Usage and highlighting for interface elements" section):

  "Button: Bold on labels and tooltip names"

- Red Hat Supplementary Style Guide ("[User interface elements](https://redhat-documentation.github.io/supplementary-style-guide/#user-interface-elements)" section):

  "Bold all graphical user interface elements, including, but not limited to, menu names, menu items, button names, dialog box names, and window names. Bold the item, even if it is not clickable."

- IBM Style Guide ("Key names" section):

  "Do not highlight the names of keys."

The macros are used very often (at least in the repository for RHEL 8 and 9 docs):

- kbd: 287
- btn: 972

I wanted to ask if we follow the style guides in these cases and should replace them (or at least not add more)?

**Comment by bergerhoffer** [comment]
This is a tough one. We try to mostly decouple AsciiDoc from the SSG (outside of providing basic examples). But I know that we do have some guidance that is in conflict with each other.

We don't use these macros on OpenShift (and didn't when I was on EAP either). But some teams obviously do - I just don't know where the majority lies.

I know that some people avoided the macros initially awhile ago because of the requirement of having to add the `:experimental:` attribute to enable them (indicating it might not be a fully supported piece of functionality). But the AsciiDoc writing guide does recommend using the macros, regardless of this, see: https://redhat-documentation.github.io/asciidoc-markup-conventions/

So the SSG (and ISG) are in conflict with the AsciiDoc writing guide, and I'm not really sure what to do about it :slightly_smiling_face: I don't dislike the option of using the macros per se, I just don't like that they're enabled behind an experimental attribute. Plus the thought of updating our repo to use the macros seems pretty out of reach.

But it definitely should be used more consistently. At the very least within the same doc set, and ideally across all.  We'd probably need to start with figuring out where the majority lies in this usage, then consider a recommendation to get this guidance in sync.

**Comment by mmuehlfeldRH** [comment]
> So the SSG (and ISG) are in conflict with the AsciiDoc writing guide, and I'm not really sure what to do about it slightly_smiling_face I don't dislike the option of using the macros per se, I just don't like that they're enabled behind an experimental attribute.

It's sufficient to define it in master.adoc / main.adoc. From there it's inherited to all included files.

In the rhel-8-docs repo, we have :experimental: in common-content/_attributes.adoc and this file is included at the beginning of each master.adoc in the repo.

> Plus the thought of updating our repo to use the macros seems pretty out of reach.

It shouldn't be a recommendation, but if the decision is to not use the `btn` and `kbd` macros, it would be easy to remove `kbd:[]` and replace `btn:[name]` with `*name*` (for bold) in a mass update with a one-liner command. It only needs to be run once per repo. This way would be much easier than adding the macros.


With respect to the `menu` macro: It was rendered correctly  (bold) on the Customer Portal until spring last year but meanwhile it's rendered without bold. I filed a ticket for this problem https://issues.redhat.com/browse/CCSOPS-1966

**Comment by mportman12** [comment]
Discussed with RHEL Docs, who use these macros throughout the RHEL documentation.

Macros add semantic value and information, could be useful for automation later, and helps button and key names stand out to customers visually.. Tomas Capek does not think macros would be adversely affected by the IBM toolset change, as the toolset is intended to support Asciidoc. If uniformity across Red Hat docs is preferred, we could render the macros as bolded text in UI for uniform look in docs, if a ticket is filed to the Tooling team.

**Comment by bergerhoffer** [comment]
That's an interesting idea about updating the stylesheets to render these macro items items as bolded instead of their default look. This might be a good compromise

**Comment by mportman12** [comment]
June SSG meeting outcome: Miriam has already talked to RHEL Docs about this. Next step is to create CCSOPS ticket.

**Comment by mportman12** [comment]
Created a [CCSOPS ticket](https://issues.redhat.com/browse/CCSOPS-2018).

**Comment by mportman12** [comment]
Response from CCSOPS:

> At this time, CCSOPS is in maintenance mode and not making substantial updates to the UI. I'm going to close this ticket out as 'wont do,' as its not within our team's scope, but I am going to add the label "CCS_FutureConsideration" so that CCS may consider this request for the new tooling effort. Please let me know if you have any questions - thank you! 

The feedback from RHEL docs was that switching the macros to bolding would be an onerous amount of work, so I think this may be the end of the line for this ticket.

**Comment by mportman12** [comment]
@joaedwar I'd like to discuss this with the Style Council before we close the ticket. It was on the (short) agenda for the July meeting that got canceled, so we'll discuss at the August meeting. I've added an On hold label to this ticket for now.

**Comment by bburt-rh** [comment]
@mportman12 Where does this issue stand at the moment? Any updates?

**Comment by mportman12** [comment]
Discussed at the August Style Council meeting. We decided to close this ticket without making changes. RHEL Docs should continue to use macros to maintain consistency within RHEL.
