### ISSUE TITLE
Does the SSG need to provide guidance for terms to refer to YAML code? If so, what should this guidance be?

### ISSUE THREAD

**Issue by bburt-rh** [redhat-documentation/supplementary-style-guide#343]
At Red Hat, we often provide YAML code samples. However, after searching in both the IBM Style guide and the SSG, I can't find any guidance for recommended or required ways to refer to specific parts of sample YAML code. For example, our current docs refer to what should be a "value" in a key:value pair as "value", "parameter", "option", etc. (instances of the different usages can be found throughout the OpenShift docs, for example).

So, there are two related issues here:

- Should we offer guidance to specify wording when citing sample YAML code?
- If we offer guidance, what should it be?

My own tendency is not to be prescriptive and leave the word usage at the discretion of the writer, depending on what they are documenting. But because YAML has key:value pairs, there's probably a case to be made that we should always refer to "keys" and "values" when specifically citing items in sample YAML code.

**Comment by mramendi** [comment]
My problem with "key" is that this little words means too many things. So when I write a list of "supported configuration keys" some of which can be "encryption keys" and one of them might be "key" for making it work, that won't be very readable, especially to a non-native English speaker.

I currently list configuration "parameters" but another writer in the same doc lists "fields" and we really need to agree on something.

**Comment by bergerhoffer** [comment]
I think this is a hard one, because I've looked into it before. 

I'd first like to say that, even if we can agree on something, I'm not sure if the SSG is the right place for this (because we don't get into details on the many other languages that we document code blocks for, and I'm not sure if we should start now).

But outside of that, I think it might be hard to agree. Normally, I'd say that we should be calling them according to what the YAML spec [1] calls them. But they don't seem to have a generic name for any field. They are called scalars or mappings, etc. depending on what the type is. But that seems overly complicated to me to determine what type the field is to know how to refer to it.

If you can't tell from my answer :wink: , I use "field", because it seems generic enough, easy to understand by users, and I see it used elsewhere. You could probably make an argument for other options though. I do see "parameter" sometimes too, and the API docs use "property". key/value pair makes sense to me when used together, but is a bit more of a mouthful, and "key" standing alone could be confusing. But I'd still hesitate to really recommend any alternative in the SSG, especially if they are not the actual words that the YAML spec wants you to use. Maybe it's something that would be better discussed among the OpenShift team? 

Just my initial thoughts though.

[1] https://yaml.org/spec/1.2.2/#chapter-2-language-overview

**Comment by mramendi** [comment]
The real question, as it seems to me, appears to be whether "field" or "parameter" is preferred when configuring stuff. "Property" is specific to API objects. I kinda now suspect that "field" is a good one to apply anywhere (not just config), but I suspect it would be better to get a wider community view. @bburt-rh would it be possible to initiate this discussion in an OpenShift space?

**Comment by bburt-rh** [comment]
@bergerhoffer I agree that the SSG is not the place for this type of guidance. We don't offer similar guidance for any other languages. Guidance should be on a project-by-project basis. Therefore, I think it's best to close this issue.

@mramendi Probably the best place to get started would be to post a query in the team-ocp-docs Slack channel and see what kind of discussion comes from that.
