### ISSUE TITLE
Replace "see" for link entries with "read"

### ISSUE THREAD

**Issue by ShaunaDiaz** [redhat-documentation/supplementary-style-guide#356]
Alternatively, remove the structure of a lead-in phrase to links altogether wherever possible. Where it would be too awkward to reorg or remove the text around the link, use "read." In this age of conscious language, "see" is abelist in nature and easily replaced with the precise verb. Users are accessing links to **read** the information, not "see" it. "Read" is better syntax.

Example 1:
* For additional customizations such as adding users, firewall rules, or kernel arguments to a blueprint, read link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_installing_and_managing_rhel_for_edge_images/composing-a-rhel-for-edge-image-using-image-builder-command-line_composing-installing-managing-rhel-for-edge-images#image-customizations_composing-a-rhel-for-edge-image-using-image-builder-command-line[Supported image customizations] 

* link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_installing_and_managing_rhel_for_edge_images/composing-a-rhel-for-edge-image-using-image-builder-command-line_composing-installing-managing-rhel-for-edge-images#image-customizations_composing-a-rhel-for-edge-image-using-image-builder-command-line[Supported image customizations] for adding users, firewall rules, kernel arguments, or other customizations to a blueprint.

Example 2:
Start with [Understanding MicroShift](https://access.redhat.com/documentation/en-us/microshift/4.13/html-single/getting_started/#microshift-understanding) and [Installing](https://access.redhat.com/documentation/en-us/microshift/4.13/html-single/installing/#microshift-install-rpm). Next, view the [release notes](https://access.redhat.com/documentation/en-us/microshift/4.13/html-single/release_notes/#microshift-4-13-release-notes).

*Note that on our Welcome page, the word "view" is still used. This should be fixed in the main OCP docs anyway, as it does not conform to current style "see."*

For information about Red Hat Device Edge, read the [Red Hat Device Edge overview](https://access.redhat.com/documentation/en-us/red_hat_device_edge/4/html/overview/device-edge-overview).
For information about Red Hat Enterprise Linux for Edge, read [RHEL for Edge documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/composing_installing_and_managing_rhel_for_edge_images/index).
For container platform documentation that is not specific to MicroShift, read [OpenShift Container Platform documentation](https://docs.openshift.com/container-platform/latest/welcome/index.html).

**Comment by mportman12** [comment]
The phrase "see [xyz]" is heavily prevalent both in documentation and common speech. "Read [xyz]" is not common and would read as awkward and unusual.

I am not a DEI expert by any means, so we may want to consult with the actual DEI group on this. From a quick Google search, I found a couple of blog posts by vision-impaired individuals stating that words like "see" and "look" are not offensive to them. I couldn't find anything on the first two pages of Google about "see" being ableist language. @ShaunaDiaz if you have found a resource about this that you can share, that would be great.

FWIW, I did find a [couple](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/accessibility-terms) [of pages](https://ncdj.org/style-guide/) about avoiding ablelist language that all use the term "see [xyz]".

**Comment by ShaunaDiaz** [comment]
@mportman12 I know someone with blindness that hates the term. I can't speak to what is published on the internet by certain groups. Ubiquity doesn't make something correct. Do we have a DEI group for people with sight impairments? I haven't seen one. That's a great idea.

**Comment by bergerhoffer** [comment]
I've already weighed in with my thoughts on the initial issue with @ShaunaDiaz where this was discussed, so I don't want to comment here until others have a chance to give their thoughts. 

@redhat-documentation/ccs-style-council PTAL!

CC @neal-timpe too, in case you want to weigh in, or if you have any ideas of who else might be good to run this by?

**Comment by ndeevy** [comment]
My only thoughts are similar to what Miriam said and also that consistency is crucial.  Because the SSG guides writers, it would make sense to include all docs in such a change and I think that would possibly be an enormous overhead and campaign to achieve. It's doable but a big job.
There also might be many instances where word craft is needed to make it read and flow easily, which might be a challenge for some writers or might impact consistency. 

_Side anecdote with no data or citations: I worked for a social organization in Germany where many of my colleagues were visually impaired or had other disabilities and they said using those types of words was fine and they would use them too. Like, "look at this" "see what I mean" etc. One friend said they felt it would be weird and draw more attention to the disability to edit the way everyone used visual/sight based words because we do it so much. That was in the German language though so it might be different in an English language or US context._

It'll be interesting to know what experts have to say on the topic.

**Comment by IngridT1** [comment]
We've had this discussion before. I thought it was in the CCS Style Council, but I can't find it in the minutes or notes. Maybe someone else can remember where to look? @neal-timpe? We don't seem to have it as an open issue here, so maybe it was in the CCSA11y? 

Anyway, @ndeevy's experience is similar to what we heard from the people that we contacted. "See" is clearer than using "read" or "refer to" and is readily understood by everyone. I think that some CCS writers wanted to deviate from IBM Style's guidance and use "refer to" instead of "see". "Read" is a new possibility. But it runs into it's own issues, because it also implies vision. "Read" is also inaccurate if you're sending someone to a video or other type of media. 

I think it's important to be sensitive with language, but to make this level of change would require oversight by the Conscious Language Initiative within Red Hat. They may have already discussed this term. We could check with them.

**Comment by neal-timpe** [comment]
Thanks for tagging me in. 

@IngridT1 I don't see an issue in our CCSA11Y jira, but I don't think that's where we would have added it. I remember having this discussion before, but I'm not sure where we might have put the issue, or if it happened in slack. 

I think checking with the Conscious Language Initiative and the Diverse Abilities group at RH might be a good next step.

**Comment by mportman12** [comment]
Thanks  all for weighing in. I've contacted both the Conscious Language Initiative and the Diverse Ability group about this topic.

**Comment by bergerhoffer** [comment]
@IngridT1 the discussion you're probably thinking of was with the IBM Style Council last year.

**Comment by IngridT1** [comment]
Thanks, @bergerhoffer!

**Comment by mportman12** [comment]
I got a few responses from the Diverse Abilities group, which I'll summarize:

- Someone who developed severe vision issues over time said they didn't find the term "see" problematic, but that may be influenced by their previous language pattern from before they developed vision issues.
- Someone with severe vision issues did not find the term "see" problematic, and said that they knew many vision-impaired people who felt similarly. They felt not bending the language would make them feel more comfortable and preferred not to update the terminology.
- Someone with minor vision issues did not find the term "see" problematic, but believed we should update our terminology if others are offended. They did not think "read" would be an inclusive alternative for people with cognitive disabilities such as dyslexia.

I do not think my email to the Conscious Language group went through, as it seems to require an approval from someone. I'm going to make another attempt to contact them and see what they think.

**Comment by mportman12** [comment]
@bergerhoffer and I discussed this topic with some folks from the IBM style guide. The reason why the SSG dictates to use "see" instead of "refer to" is because that's what the ISG dictates. This was mainly because "see" is fewer words than "refer to". The IBM folks are going to discuss with the rest of the IBM style group and decide whether to alter their guide to allow "refer to".

**Comment by ShaunaDiaz** [comment]
@mportman12 Thanks so much, but I am not interested in using "refer to."

**Comment by bergerhoffer** [comment]
@ShaunaDiaz are you saying that you're only interested in using "read" and no other possible alternative to "see"?

**Comment by mportman12** [comment]
@ShaunaDiaz Do you have any specific objections to "refer to"?

**Comment by ShaunaDiaz** [comment]
@mportman12 The style guide prohibits it now, so that'll just be more rounds of effort and more socialization. I think it's very clear that "read" isn't going to be acceptable, which was my request. "Read" is already in my docs and will have to be changed, clearly. Since that work is required and there are mixed in "sees," I prefer to create a backlog issue to swap in "see" for all of the "read" instances and move on. It's the quickest path to resolving this issue. I need to focus on the documentation at large, not a single word.

**Comment by bergerhoffer** [comment]
@ShaunaDiaz we still had some discussions in progress with the IBM style council (and they are planning to discuss among themselves). Did you not want to hear the outcome of the discussions on the IBM side?

**Comment by bergerhoffer** [comment]
@ShaunaDiaz Yeah, we're waiting to hear back from the IBM style council after they discuss among themselves. We'll keep you updated when we hear something. Thanks!

**Comment by bburt-rh** [comment]
@mportman12 @bergerhoffer - I don't remember where we left this one after the last style council meeting. Can we close this? Or are we still waiting on IBM style council feedback?

**Comment by mportman12** [comment]
@bburt-rh Waiting to hear back from IBM still.

**Comment by bburt-rh** [comment]
Thanks @IngridT1 and @mportman12. I am closing this issue per our discussion in meeting.

**Comment by bergerhoffer** [comment]
Hi Shauna,

I noticed that this issue has already been closed, but wanted to report back some additional information. We just got off of the call where the IBM Style Council representatives reported back after discussing this issue with the rest of the IBM Style Council.

They reported that the IBM Style Council came to the decision that they don’t think that using the term “see” is offensive and they think it’s the right term to continue to use. They do have an accessibility expert on the council, who checked the current accessibility guidelines and felt that it was not problematic to use.

Based on other discussions that have gone on throughout Red Hat (supplementary style guide, diverse abilities, and accessibility groups), we feel that “see” is still the right term to continue to use.
