### ISSUE TITLE
Spelling out digits under ten

### ISSUE THREAD

**Issue by mportman12** [redhat-documentation/supplementary-style-guide#455]
The SSG does not contain any guidance about whether to spell out digits under ten (i.e. one vs. 1 etc.). The ISG says its fine to use either words or numerals, but to be consistent within the document.

Because the ISG does not have a firm position either way, I think we should pick a side and update the SSG so that all Red Hat product docs are consistent.

**Comment by mportman12** [comment]
Google Style Guide spells out digits under ten, fwiw https://developers.google.com/style/numbers

**Comment by bburt-rh** [comment]
I think we should add guidance to spell out any whole numbers under ten, and use numerals for everything else.

**Comment by bergerhoffer** [comment]
I think we need to be careful about it, because there are plenty of places where I think it could make better sense to use numerals. I wouldn't want to put a blanket "spell out everything under 10" guideline and then have people spell out places that don't make sense.

**Comment by bergerhoffer** [comment]
Update from the March 27 SSG meeting: 

Adding guidance might be a bit difficult. There are a lot of other good sources of guidance on this (Google style guide, Microsoft style guide, Chicago manual of style. 

Perhaps a compromise would be to add a collection of examples to the SSG of when to use words vs. numerals for digits under 10.

First step is to collect some examples in this issue of when we think numerals are more suited, or when words are more suited.

@redhat-documentation/ccs-style-council Putting out a call to add your examples here of when you think numerals or words are more appropriate.

**Comment by dfitzmau** [comment]
Here is an example of a product name that chosses a word over a numeral: 

[three-node cluster on AWS](https://docs.openshift.com/container-platform/4.15/installing/installing_aws/installing-aws-three-node.html)

Yet,[3scale](https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.14).

Conclusion: Check product name spellings and preserve their name; no exceptions.

**Comment by bredamc** [comment]
I think that we don't need to update the SSG, because the current advice in the ISG is sufficient. 

The ISG formerly advised the use of the spelled-out form for numbers under ten. I suspect that, similar to @bergerhoffer's concern above, the ISG deliberately no longer provides a blanket rule for all cases, so that people can choose the correct option to suit each individual case. The important thing is, as mentioned in the ISG: 
"Within a publication, be consistent in your approach." 

Having said all of that, you asked for examples. I think the numeral is better in the following case:

Scroll down to review the following graphs:
- Top 5 items doing x
- Top 5 items doing y

**Comment by sbmetz** [comment]
A few examples where I think digits are better:
* Dates (January 8, 2024, for example, in release notes)
* Ages/time length ("certificate is more than 5 years old")
* Percents ("every 5 percent increase over 50 percent")
* Ratios ("2-to-1 mapping")

**Comment by mportman12** [comment]
IBM Style said they changed their guidance to allow numerals based on this article, which said that using numerals stand out better on the page when readers are scanning material instead of reading in-depth: https://www.nngroup.com/articles/web-writing-show-numbers-as-numerals/

**Comment by bredamc** [comment]
It seems that the change in preference from using words to using numbers is primarily because our documentation is now mainly online rather than printed, although the ISG does provide several examples where the words are better. I still think that the advice in the ISG covers all cases, and we don't need separate advice in the SSG :)

**Comment by bergerhoffer** [comment]
Discussed at the 31 July SSG meeting.

We heard an update about some additional information from the IBM Style Council about why they changed their guidance to allow numerals (https://www.nngroup.com/articles/web-writing-show-numbers-as-numerals/).

We agreed that we should close out this issue without making an update to the SSG. A handful of people were in favor of preferring numerals, but some preferred spelling out. Instead of trying to favor one or the other, which would still require providing caveats, we agreed to not make any updates to the SSG and instead follow the ISG's guidance. Closing this out.
