### ISSUE TITLE
Include Conscious Language Initiative words

### ISSUE THREAD

**Issue by jafiala** [redhat-documentation/supplementary-style-guide#46]
We should include the recommendations from the [Conscious Language Initiative](https://source.redhat.com/aboutredhat/weareredhat/diversity/diversity__inclusion_wiki/conscious_language_project_faq).
Blacklist/whitelist are not included in the SSG but should be.
Master/slave is referred to and should not be.

**Comment by bergerhoffer** [comment]
Great suggestion. We can definitely add blacklist/whitelist as general entries, saying to either write around it or to use one of the listed alternatives, due to conscious language reasons.

Master/slave is going to be more complicated, because some of these might still be used in the product, and docs can't completely remove the references until the products do. My initial thoughts would be to:

1. Add general entries for master and slave, recommending to avoid these terms if at all possible, but making sure that the docs are still in sync with the terms used in the product, and provide the list of alternatives.
2. Review the instances of master and slave in the SSG and see which ones can be updated. We will probably have to reach out to individual product teams for product-specific entries (for example, "Master Boot Record").

**Comment by jafiala** [comment]
Thanks Andrea, that sounds like a good solution. I mean, white/blacklist is also still used in places but we're moving away from those quite soon.

I definitely second "write around it or use one of the listed alternatives" in this order. Many instances of "whitelisting" are actually jargon and can be rewritten more clearly, even if one were to neglect the CLI reasons.

**Comment by cbudz** [comment]
@bergerhoffer @jafiala It might be best to touch base with Kartik and see what plans they have fo updating terms across documentation groups and best align with the initiative. I noticed we have a good number of glossary entries for specific products that would need updating.

**Comment by leswilliams44** [comment]
@cbudz, Kartik is going to talk about conscious language at the Jan 14 CCS Best Practices meeting. Yet one channel to get the word out.

**Comment by jafiala** [comment]
> @bergerhoffer @jafiala It might be best to touch base with Kartik and see what plans they have fo updating terms across documentation groups and best align with the initiative.

Sure, I am actually participating in this initiative in updating some of RHEL security docs. This just felt like a place where such terms should be mentioned so that our future docs are aligned with it and we don't have to fix it retrospectively.

**Comment by cbudz** [comment]
@jafiala fully agreed. This is ideally the space for that guidance moving forward.

**Comment by cbudz** [comment]
@jafiala are you willing to help us coordinate updates on our end since you're participating in the initiative?

**Comment by jafiala** [comment]
@cbudz Willing sure, but not sure what it entails. Let's discuss this separately, if you don't mind.

**Comment by leswilliams44** [comment]
Hi, @jafiala and @cbudz. Do you have an update for this issue?

**Comment by jafiala** [comment]
Hi Les. We discussed this in the push request. Since explicit and sufficient guidance for these terms is part of the new version of the IBM Style Guide, we decided not to duplicate it in the supplementary guide. I closed the push request but had not closed this suggestion. I'm closing this now.
