### ISSUE TITLE
Guidelines for writing abstracts in documentation 

### ISSUE THREAD

**Issue by cbudz** [redhat-documentation/supplementary-style-guide#75]
Carried over from CCS discussion. 

We need to:

- Define abstract. 
- Determine where in a doc the abstract goes.
- Define short description. 
- Differentiate between an abstract and a short description at the module level or adopt a single term if they are both the same. 
- Provide style guidelines with examples
- Update existing topics to reflect changes

**Comment by leswilliams44** [comment]
Do we have any reference material to consult as a starting point?

**Comment by jhoyt-rh** [comment]
Wondering where the decision to include Abstracts came from. I don't find it in the IBM Style Guide. Do we have an idea of why it was decided to have abstracts in the first place (and where to have them)? Perhaps if we did, we would know the problem they were attempting to solve by having them. And that might provide some guidance.

Also, IF we decided to have them, but use one term for both abstracts and short descriptions, what about Precis? Or does that seem too non-technical?

**Comment by leswilliams44** [comment]
@jhoyt-rh, Abstracts are one way we can improve SEO results. JP Sherman has conducted a lot of talks about this and is trying to help up make our documents more findable.

Abstracts are considered front (prefatory) matter.

Hope that helps a bit.

**Comment by samccann** [comment]
There were two abstracts talked about in the original CCS email thread:

- At the document level as seen here - https://access.redhat.com/documentation/en-us/red_hat_hyperconverged_infrastructure_for_virtualization/1.8/html-single/upgrading_red_hat_hyperconverged_infrastructure_for_virtualization/index?lb_target=preview
- At the individual module level as recently added to the mod-docs templates, as seen here - https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_REFERENCE_reference-material.adoc

Can we clarify which of the above we want to call 'abstract' and which we may want to call something else, such as shortdescription?  (and if both actually impact SEO?).

And also could someone summarize here, as was asked earlier - where and why did the new moddocs templates add an abstract section to each module type? It's unclear to me if what I put in the module level abstract is effectively the first paragraph in my module (and for a reference module, perhaps the only paragraph needed before the actual reference material.)

As an addendum, while this is a DITA reference, it helped me understand how the two can be different (at least in that world) - https://www.oxygenxml.com/dita/styleguide/webhelp-feedback/Artefact/Syntax_and_Markup/c_Short_Descriptions.html

**Comment by inoxx03** [comment]
@redhat-documentation/ccs-style-council
What are the terms that we should go with for the front-matter abstract vs. the assembly or module-specific  abstract?
I don't recall whether we achieved consensus, yet.
Is it _abstract_ for the prefatory one and  _short-description_ for the one in modules and assemblies?

Personally, I'd use _abstract_ for the ones in modules and assemblies, because they are a more recent addition to our style and likely to also apply to Pantheon 2 content (whereas the prefatory ones are specific to Pantheon 1 and might be retired with Pantheon 1).

Then again, both are currently referred to by the same term, so I'mo mindful of the potential for creating some confusion here.
Also, apologies if I'm misunderstanding the situation, please feel free to correct me if that's the case:)

Please let me know your thoughts.


Thank you!

**Comment by inoxx03** [comment]
@redhat-documentation/ccs-style-council 
OK, I suppose I may have been overthinking things a bit when I wrote my previous question:)

Here's what I'm going with a after some consideration:

I'll disregard the prefatory DocBook abstract for now and focus on providing guidelines for writing the abstracts that we are required to have in modules and assemblies.
This is largely due to our ongoing effort to migrate to Pantheon 2, where the original title-level abstracts are not going to be used, because we are moving away form using titles altogether to publish individual assemblies. 

We can tweak the details when I have submitted  the PR.

**Comment by mportman12** [comment]
@inoxx03 Can you create a PR for this issue and add guidelines for writing abstracts?

**Comment by inoxx03** [comment]
Hi, @mportman12  Yes, absolutely. Apologies for the lag :)

**Comment by bergerhoffer** [comment]
@inoxx03 Is this something you can work on in the near future?

**Comment by daobrien** [comment]
Perhaps you could start with the existing material that CCS put together some time back:
https://stylepedia.net/style/5.0/#abstracts

It hasn't been updated for a while and might need some tweaking, but all the basics are there.

**Comment by stoobie** [comment]
@inoxx03 The Mod Docs guide doesn't use the word "abstract". The "_abstract" tag is a Pv2 requirement/suggestion (See the Pv2 EUD PR on usage guidance for Pv2 https://github.com/redhataccess/pantheon/pull/621). Here's the mod docs guidance related to module abstracts copied from the guide:

= Concept Introduction

The introduction to a concept module is a single, concise paragraph that provides a short overview of the module. A short description makes the module more usable because users can quickly determine whether the concept is useful without having to read the entire module.

The introduction typically answers the following questions:

    What is the concept?

    Why should the user care about the concept?

= Procedure Introduction

The introduction is a short description of the procedure. For example, it can be a lead-in sentence or an infinitive phrase (To extract the certificate: <steps>). See also The IBM Style Guide [1] for details on introducing procedures.

The introduction typically provides context for the procedure, such as:

- Who is the user performing the procedure
- Why and where the user performs the procedure
- Special considerations specific to the procedure

Keep the information brief and focused on what the user needs for this specific procedure. Suggested length is 1—​3 sentences, but it can be longer.

= Reference Introduction

The introduction to a reference module is a single, concise paragraph that provides a short overview of the module. A short description makes the module more usable because users can quickly determine whether the reference is useful without having to read the entire module.

**Comment by stoobie** [comment]
@inoxx03 Let's get JP Sherman's input. I'll ping him because I don't know his Github handle.

**Comment by stoobie** [comment]
@inoxx03 It's very important that any guidelines we provide on usage considers Pv2 (and SEO) requirements, for example, an abstract needs to be in one paragraph. That's often counter-intuitive. For example, it means _not_ using bulleted lists to list a sequence of items.

**Comment by inoxx03** [comment]
@stoobie Thank you for summarizing the rules for introductory paragraphs above. I'll make sure to include them in the section when I create the PR. 

As far as formatting specifics go, If I remember correctly, there should be no blank line between the [role="_abstract"] tag and the intro paragraph, either.

Finally, regarding the use of the term "abstract", I realize that Pantheon 2 does not use the term to denote an introductory paragraph. Personally, I wouldn't use it either, given that we use the same term for the short title summary in the `master-docinfo.xml` files in Pantheon 1.

I would say "introductory paragraph" or "module introduction" instead, WDYT?

**Comment by bergerhoffer** [comment]
Closing this, since intro content is being worked through issue #168
