### ISSUE TITLE
Suggest adding "standalone"

### ISSUE THREAD

**Issue by ncbaratta** [redhat-documentation/supplementary-style-guide#76]
The ISG says to put the hyphen in stand-alone, but it appears that most of our products (if not all) have this as one word already.  I recommend adding it to the guide as an exception to the ISG.

**Comment by msve** [comment]
For EAP we already use standalone (without hyphen) in a lot of places, because that's the name of one of the server modes and name of the default configuration. We feel that using the form with hyphen might be confusing for users and it would introduce an extra burden for doc and QE teams (we will have to particularly careful with where to use which of the two forms).

So from EAP QE we support this change to use standalone without hyphen in our documentation.

**Comment by dfitzmau** [comment]
Thanks, Nicole and Martin. I also agree with keeping the "standalone" term based on the use of the term both in upstream and downstream environments.

**Comment by bergerhoffer** [comment]
To be clear here, you're not asking that we always use "standalone" in favor of "stand-alone", but instead asking to add an entry for "standalone" to say that it's an acceptable usage when the product you're writing for uses that terminology?

**Comment by ncbaratta** [comment]
@bergerhoffer the discussion was here: https://chat.google.com/room/AAAAAjCmTJI/WvJeFjdYbHg but in short, the guides all seem to have `standalone` but the new IBM Styleguide says to use `stand-alone`.  So we want it in the supplementary style guide to say it's okay to ignore this rule in the IBM Styleguide and instead use the standard we already have in place across most of our products (if not all).

**Comment by bergerhoffer** [comment]
Decision from the May 5 project meeting - add an entry to the SSG to add "standalone" as the preferred form (over "stand-alone"). This is not product-specific (to EAP or any others), but will be our general guidance for the term across product docs.

@cbudz to draft PR.

**Comment by sterobin** [comment]
Addressed in PR #89 . Pending approval and merge.

**Comment by bergerhoffer** [comment]
PR has been merged, closing!
