### ISSUE TITLE
"As expected"

### ISSUE THREAD

**Issue by mjahoda** [redhat-documentation/supplementary-style-guide#83]
Because the IBM Style Guide (IMHO incorrectly) uses "as expected" a lot and I haven't found any written guideline regarding this, I am proposing to add something along the following to the Supplementary style guide:

"as expected" - expectations are relative and do not belong to technical documentation. Use "correctly" or "properly" instead.

**Comment by jafiala** [comment]
I second this (although, full disclosure, I learned this from mjahoda).

I think the main argument against using "as expected" is that we cannot assume users' expectations. For example, a tester might _expect_ a task to fail, but that does not mean the task functions correctly.

**Comment by jherrman** [comment]
This is definitely a fair point, though if I remember correctly, "as expected" is meant to be a more user-focused version of "as intended" (meaning to say the software does what it's bloody supposed to in a given situation). 

On top of that, you could find not-dissimilar issues with the meanings of "correctly" [1] and "properly" [2], too.

[1] I think what @jafiala points out is actually an argument _for_ using "as expected", since in scenarios where we talk about things failing/crashing (instead of e.g. risking hardware damage), "correctly" would be a strange term to use. In addition, there is the potential theme/rheme ambiguity of e.g. "program X does Y correctly" and "program X correctly does Y".

[2] "Proper" is a term strongly associated with a societal expectations, so "do something properly" can mean different things to different people.

So, overall, I'd be against this proposal, given that:

- "As expected" covers situations when "correctly" or "properly" would be stylistically awkward 
- "As expected" is already heavily used in our existing docs and removing it would mean overhead
- None of the terms at our disposal is 100% perfect anyway

**Comment by mjahoda** [comment]
@jherrman As I am reading through your comment, I am regretting that I forgot to add "as intended" to this issue :-)

To your point [1] - I am not a native speaker and I do not see anything strange using "correctly" in the mentioned scenarios.

Regarding [2] - well, I also feel that "correct" is more appropriate than "properly" in technical docs

Speaking of the removal from all existing docs - I believe that having this as a recommendation and agreeing that there is no requirement for an immediate bulk action can resolve this concern.

**Comment by ndeevy** [comment]
Hi!  my 2 cents:

I also dislike and remove "as intended/expected" but also for an additional reason: it's passive. Who or what expects/intends the behaviour? nobody knows usually.

"Correctly" and "properly" both have the element of not knowing what that might mean precisely but I think it's better than "as intended/expected". However, I agree with @jherrman   that 'properly" should not be used because it has weird connotations in terms of societal norms/politeness and stuff like that.

Also agree with @mjahoda  that the recommendation could be more like: from now on do this or if you encounter it in your travels, change it rather than a legacy overhaul.

**Comment by bergerhoffer** [comment]
We discussed this in the 23 June style council meeting and agreed that there are often better alternatives to using "as expected" and that we can add an entry for it.

@mjahoda Would you mind opening a PR to add an entry for "as expected" with recommended guidance against it, and provide some alternatives?

**Comment by mjahoda** [comment]
@bergerhoffer I am just wondering if I should add the term as:

1. as expected -> a.adoc
2. expected -> e.adoc (adverb)
3. expect, expected -> e.adoc (verb, adverb) 
4. any other suggestions? (+ create also an entry for "as intended" and xref each other)

**Comment by mportman12** [comment]
@mjahoda I vote for as expected -> a.adoc. While the IBM Style Guide doesn't give guidance for `as expected`, it does give guidance for other `as <word>` terms and lists them under the letter A.

**Comment by mjahoda** [comment]
I put "as expected" to a.adoc as Miriam voted, and I opened a PR:

https://github.com/mjahoda/supplementary-style-guide/pull/1/files

**Comment by bergerhoffer** [comment]
@mjahoda thanks! I reviewed the PR, but it is in your personal fork. Can you please open it as a PR in this upstream repository [1]?

[1] https://github.com/redhat-documentation/supplementary-style-guide/pulls

**Comment by mjahoda** [comment]
Resolved by https://github.com/redhat-documentation/supplementary-style-guide/pull/112
